/**
 * V.3 — Trade-offs. What each choice costs: bytes on the wire (full state vs delta vs one op, with
 * the real `size` the reducer computes), delivery guarantees ops need, metadata that never leaves
 * (RGA tombstones with `expose:['stats']`, OR-Set tags), and why garbage collection needs
 * agreement. Storyboard: docs/curriculum/unit-5-prototypes.md §V.3.
 */
import {
  topic,
  scene,
  step,
  alice,
  bob,
  carol,
  board,
  meter,
  tick,
  offline,
  online,
  set,
  drop,
  highlight,
  callout,
  check,
  cross,
  clearMarks,
  same,
  expect,
  bad,
  good,
  merge,
  apply,
  crdt,
  seed,
  lwwMap,
  orSet,
  rga,
} from '@/lesson/builders'

const DOC_SEED = [
  seed('set', 'title', 'Fix login'),
  seed('set', 'owner', 'Ann'),
  seed('set', 'due', 'Fri'),
  seed('set', 'status', 'open'),
]

/** Bytes of the messages this scene sends, measured from the reducer (`crdt.send` sets `size`). */
const FULL_BYTES = 200
const DELTA_BYTES = 57
const WIRE_MAX = 240

export default topic({
  id: 'tradeoffs',
  title: 'Trade-offs',
  goal: 'Name what each choice costs — bytes on the wire, delivery guarantees, metadata that never leaves — and pick the cheaper option for a given workload.',
  whenToUse: [
    'State-based: small state, lossy or reordering networks, few replicas, simplest code.',
    'Delta-state: state-based safety with op-sized messages; most real systems do this.',
    'Op-based: big documents with small frequent edits, plus reliable causal delivery.',
    'Garbage collection: when every replica is known and can say what it has seen.',
  ],
  whenNotToUse: [
    'Do not send the full state of a large document on every keystroke.',
    'Do not go op-based without exactly-once, causal delivery, or a log you can replay.',
    'Do not drop a tombstone while any copy may still hold the old item: it comes back.',
    'Do not promise small metadata for long-lived text without a clean-up plan.',
  ],
  realWorld:
    'A likes counter across three data centres (tiny state, sync it whole) against a document typed in for a year (small edits, big history, and a garbage collection plan).',
  scenes: [
    scene(
      'state-or-ops',
      {
        layout: 'pair',
        clock: { show: true },
        actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' })],
        boards: [
          board('full', meter(0, WIRE_MAX, 'full state'), { label: 'bytes sent' }),
          board('delta', meter(0, WIRE_MAX, 'delta'), { label: 'bytes sent' }),
        ],
      },
      [
        step(
          's01',
          'The same four-field document, kept twice on each device: one copy syncs by whole state, the other by operations.',
          crdt.init(['alice', 'bob'], 'state', 'lww-map', { seed: DOC_SEED }),
          crdt.init(['alice', 'bob'], 'ops', 'lww-map', { seed: DOC_SEED, wire: 'ops' }),
          callout('alice.state', 'state-based', { sticky: true, id: 'k1' }),
          callout('alice.ops', 'op-based', { sticky: true, id: 'k2' }),
        ),
        step(
          's02',
          'Time 1. Alice changes one field, the owner, in both copies.',
          tick(),
          lwwMap('state').set('alice', 'owner', 'Bob'),
          lwwMap('ops').set('alice', 'owner', 'Bob'),
          expect('alice.state.owner', 'Bob'),
        ),
        step(
          's03',
          'State-based: Alice sends her whole document. All four fields travel for one change, and the token shows the byte count.',
          crdt.send('alice', 'bob', 'state', { id: 'm1', mode: 'full', label: 'whole state' }),
          merge('m1'),
          set('board.full', meter(FULL_BYTES, WIRE_MAX, 'full state')),
          expect('bob.state.owner', 'Bob'),
        ),
        step(
          's04',
          'Op-based: she sends one operation instead — the one write she did.',
          crdt.broadcast('alice', 'ops', { id: 'op1', to: ['bob'] }),
          apply('op1@bob'),
          expect('bob.ops.owner', 'Bob'),
        ),
        step(
          's05',
          'Time 2. Alice closes the task in both copies, sends both ways, and this time the network loses both messages.',
          tick(),
          lwwMap('state').set('alice', 'status', 'done'),
          lwwMap('ops').set('alice', 'status', 'done'),
          crdt.send('alice', 'bob', 'state', { id: 'm2', mode: 'full' }),
          crdt.broadcast('alice', 'ops', { id: 'op2', to: ['bob'] }),
          drop('m2'),
          drop('op2@bob'),
        ),
        step(
          's06',
          'State-based: no harm done. The next sync carries the whole state again, and merging the same state twice changes nothing.',
          crdt.send('alice', 'bob', 'state', { id: 'm3', mode: 'full' }),
          merge('m3'),
          check('bob.state.status'),
          expect('bob.state.status', 'done'),
        ),
        step(
          's07',
          'Op-based: that operation is gone. Bob still reads open, and nothing on his side knows it is stale.',
          bad('bob.ops.status'),
          cross('bob.ops.status'),
          expect('bob.ops.status', 'open'),
        ),
        step(
          's08',
          'The fix: keep a log of your operations, compare what each side has, and resend the missing ones.',
          clearMarks(),
          crdt.sync('alice', 'bob', 'ops', { mode: 'ops' }),
          apply('alice:2@bob'),
          good('bob.ops.status'),
          expect('bob.ops.status', 'done'),
        ),
        step(
          's09',
          'Time 3. The middle ground: Alice edits again and sends only the change, as a delta (simplified).',
          clearMarks(),
          tick(),
          lwwMap('state').set('alice', 'due', 'Mon'),
          crdt.send('alice', 'bob', 'state', { id: 'm4', mode: 'delta', label: 'delta' }),
          merge('m4'),
          set('board.delta', meter(DELTA_BYTES, WIRE_MAX, 'delta')),
          expect('bob.state.due', 'Mon'),
        ),
        step(
          's10',
          'The delta was 57 bytes against 200 for the full state, and the same merge accepts both. It is still safe to lose or apply twice.',
          highlight(['board.full', 'board.delta']),
          same('alice.state', 'bob.state'),
        ),
        step.long(
          's11',
          'State means big messages on any network; ops mean small messages that must all arrive. A delta sits between, if you can resend a lost one.',
        ),
      ],
    ),
    scene(
      'metadata-stays',
      {
        layout: 'pair',
        actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' })],
      },
      [
        step(
          's01',
          'Alice types the word hello into a shared note: five items, each with its own id. Bob syncs and has the same five.',
          crdt.init(['alice', 'bob'], 'note', 'rga', {
            display: 'text',
            expose: ['stats'],
          }),
          rga('note').type('alice', 'HEAD', 'hello'),
          crdt.sync('alice', 'bob', 'note'),
          expect('alice.note', 'hello'),
          expect('alice.note@stats', { stored: 5, visible: 5 }),
        ),
        step('s02', 'Bob goes offline.', offline('bob')),
        step(
          's03',
          'Alice deletes all five letters. They do not leave: each one becomes a **tombstone**.',
          rga('note').deleteRange('alice', 'alice:1', 'alice:5'),
          highlight('alice.note@stats'),
          expect('alice.note', ''),
          expect('alice.note@stats', { stored: 5, visible: 0 }),
        ),
        step(
          's04',
          'She types hi instead. The note shows 2 letters, and stores 7 items.',
          rga('note').type('alice', 'HEAD', 'hi'),
          highlight('alice.note@stats'),
          expect('alice.note', 'hi'),
          expect('alice.note@stats', { stored: 7, visible: 2 }),
        ),
        step(
          's05',
          'Why keep the dead ones? Because Bob is back, and his copy still spells hello.',
          online('bob'),
          highlight('bob.note'),
          expect('bob.note', 'hello'),
        ),
        step(
          's06',
          "Merge: the tombstones tell Bob's copy that those five are deleted, so both now read hi. Without the markers, they would come back.",
          crdt.sync('alice', 'bob', 'note'),
          same('alice.note', 'bob.note'),
          expect('bob.note', 'hi'),
          expect('bob.note@stats', { stored: 7, visible: 2 }),
        ),
        step(
          's07',
          'After a year of writing and deleting, the markers are most of the document. That is the price of never forgetting.',
          callout('alice.note@stats', 'stored is much more than visible', {
            tone: 'warn',
            sticky: true,
            id: 'k1',
          }),
        ),
        step(
          's08',
          'Sets pay the same way. Every add mints a tag, and the tags stay on the element after the remove.',
          clearMarks(),
          crdt.init(['alice', 'bob'], 'cart', 'or-set'),
          orSet('cart').add('alice', 'milk'),
          crdt.sync('alice', 'bob', 'cart'),
          orSet('cart').remove('bob', 'milk'),
          crdt.sync('alice', 'bob', 'cart'),
          orSet('cart').add('alice', 'milk'),
          crdt.sync('alice', 'bob', 'cart'),
          highlight('alice.cart[milk]@tags'),
          expect('alice.cart[milk]@tags', [
            { tag: 'alice:1', alive: false },
            { tag: 'alice:2', alive: true },
          ]),
        ),
        step(
          's09',
          'One item in the cart, two tags stored on it, and one of them dead for good. A 2P-Set is worse: its removed set only grows.',
          highlight('bob.cart[milk]@tags'),
          expect('bob.cart', ['milk']),
        ),
        step.long(
          's10',
          'Real libraries make this smaller, not zero: Yjs stores deleted runs as id ranges, Automerge packs its history in columns. Both still remember every delete.',
        ),
      ],
    ),
    scene(
      'cleaning-up',
      {
        layout: 'triangle',
        actors: [alice(), bob(), carol()],
      },
      [
        step(
          's01',
          'Three copies of one list. Everyone has seen a, b and c.',
          crdt.init(['alice', 'bob', 'carol'], 'list', 'rga', {
            expose: ['stats', 'vc'],
            seed: [
              seed('insertAfter', 'HEAD', 'a'),
              seed('insertAfter', 'seed:1', 'b'),
              seed('insertAfter', 'seed:2', 'c'),
            ],
          }),
          expect('alice.list', ['a', 'b', 'c']),
        ),
        step('s02', 'Carol goes offline for the day.', offline('carol')),
        step(
          's03',
          'Alice deletes b and syncs with Bob. Both keep a tombstone where b was.',
          rga('list').delete('alice', 'seed:2'),
          crdt.sync('alice', 'bob', 'list'),
          highlight(['alice.list[seed:2]@tomb', 'bob.list[seed:2]@tomb']),
          expect('alice.list', ['a', 'c']),
          expect('alice.list@stats', { stored: 3, visible: 2 }),
        ),
        step(
          's04',
          'They want the space back, so both throw the tombstone away without asking anyone (simplified).',
          clearMarks(),
          crdt.gc('alice', 'list', { unsafe: true }),
          crdt.gc('bob', 'list', { unsafe: true }),
          expect('alice.list@stats', { stored: 2, visible: 2 }),
        ),
        step(
          's05',
          'Carol comes back. Her copy still has b, and she syncs with Alice.',
          online('carol'),
          crdt.sync('alice', 'carol', 'list'),
        ),
        step(
          's06',
          'Whoops — b is back, and not even in its old place. Alice forgot the delete, so b looks like news to her.',
          bad('alice.list[seed:2]', 'deleted item is back'),
          expect('alice.list', ['a', 'c', 'b']),
          expect('alice.list@stats', { stored: 3, visible: 3 }),
        ),
        step(
          's07',
          'The rule: drop a tombstone only once every copy has seen the delete. Knowing that needs a record of who has seen what.',
          clearMarks(),
          callout('alice.list@vc', 'seen by all, then forget', { sticky: true, id: 'k1' }),
        ),
        step(
          's08',
          'Replay it, safely. Here is the same list again, and this time we watch the version vectors.',
          clearMarks(),
          crdt.init(['alice', 'bob', 'carol'], 'list2', 'rga', {
            expose: ['stats', 'vc'],
            seed: [seed('insertAfter', 'HEAD', 'a'), seed('insertAfter', 'seed:1', 'c')],
          }),
          rga('list2').insertAfter('bob', 'seed:1', 'b'),
          crdt.sync('alice', 'bob', 'list2'),
          crdt.sync('bob', 'carol', 'list2'),
          expect('alice.list2', ['a', 'b', 'c']),
          expect('alice.list2@vc', { bob: 1 }),
        ),
        step(
          's09',
          'Carol goes offline. Alice deletes b and syncs with Bob, and this time nobody cleans up.',
          offline('carol'),
          rga('list2').delete('alice', 'bob:1'),
          crdt.sync('alice', 'bob', 'list2'),
          highlight(['alice.list2@vc', 'bob.list2@vc']),
          expect('alice.list2@vc', { alice: 1, bob: 1 }),
          expect('carol.list2@vc', { bob: 1 }),
        ),
        step(
          's10',
          "Carol returns and syncs with both. All three version vectors now carry Alice's delete, so it is stable.",
          clearMarks(),
          online('carol'),
          crdt.sync('alice', 'carol', 'list2'),
          crdt.sync('bob', 'carol', 'list2'),
          highlight(['alice.list2@vc', 'bob.list2@vc', 'carol.list2@vc'], { tone: 'ok' }),
          expect('carol.list2@vc', { alice: 1, bob: 1 }),
        ),
        step(
          's11',
          'Now every copy may clean up, because every copy has seen the delete. The tombstone goes, and nothing brings b back.',
          clearMarks(),
          crdt.gc('alice', 'list2', { upTo: { alice: 1, bob: 1 } }),
          crdt.gc('bob', 'list2', { upTo: { alice: 1, bob: 1 } }),
          crdt.gc('carol', 'list2', { upTo: { alice: 1, bob: 1 } }),
          crdt.sync('alice', 'carol', 'list2'),
          same('alice.list2', 'carol.list2'),
          expect('alice.list2', ['a', 'c']),
          expect('alice.list2@stats', { stored: 2, visible: 2 }),
        ),
        step.long(
          's12',
          'A server log can find that point for you ([III.7](/crdts/operation-based/tombstones-and-garbage)). Without one, cleaning up is rare and careful.',
          check('alice.list2'),
          check('carol.list2'),
        ),
      ],
    ),
  ],
})
