/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleDesignRouteImport } from './routes/$locale/design'
import { Route as LocaleModuleIndexRouteImport } from './routes/$locale/$module/index'
import { Route as LocaleModuleUnitTopicRouteImport } from './routes/$locale/$module/$unit/$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDesignRoute = LocaleDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleModuleIndexRoute = LocaleModuleIndexRouteImport.update({
  id: '/$module/',
  path: '/$module/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleModuleUnitTopicRoute = LocaleModuleUnitTopicRouteImport.update({
  id: '/$module/$unit/$topic',
  path: '/$module/$unit/$topic',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/design': typeof LocaleDesignRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$module/': typeof LocaleModuleIndexRoute
  '/$locale/$module/$unit/$topic': typeof LocaleModuleUnitTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/design': typeof LocaleDesignRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$module': typeof LocaleModuleIndexRoute
  '/$locale/$module/$unit/$topic': typeof LocaleModuleUnitTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/design': typeof LocaleDesignRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$module/': typeof LocaleModuleIndexRoute
  '/$locale/$module/$unit/$topic': typeof LocaleModuleUnitTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/design'
    | '/$locale/'
    | '/$locale/$module/'
    | '/$locale/$module/$unit/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/design'
    | '/$locale'
    | '/$locale/$module'
    | '/$locale/$module/$unit/$topic'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/design'
    | '/$locale/'
    | '/$locale/$module/'
    | '/$locale/$module/$unit/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/design': {
      id: '/$locale/design'
      path: '/design'
      fullPath: '/$locale/design'
      preLoaderRoute: typeof LocaleDesignRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$module/': {
      id: '/$locale/$module/'
      path: '/$module'
      fullPath: '/$locale/$module/'
      preLoaderRoute: typeof LocaleModuleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$module/$unit/$topic': {
      id: '/$locale/$module/$unit/$topic'
      path: '/$module/$unit/$topic'
      fullPath: '/$locale/$module/$unit/$topic'
      preLoaderRoute: typeof LocaleModuleUnitTopicRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleDesignRoute: typeof LocaleDesignRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleModuleIndexRoute: typeof LocaleModuleIndexRoute
  LocaleModuleUnitTopicRoute: typeof LocaleModuleUnitTopicRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleDesignRoute: LocaleDesignRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleModuleIndexRoute: LocaleModuleIndexRoute,
  LocaleModuleUnitTopicRoute: LocaleModuleUnitTopicRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
