/**
 * Flow mark (reducer-generated by crdt.merge / crdt.sync): a faint accent arrow along the same arc a
 * token would travel between the two slots, drawn on with `pathLength`; double-headed when `both`.
 * Heads are explicit triangles (no <marker>) so they fade in when the line reaches them.
 */
import { motion } from 'motion/react'
import type { Mark } from '@/lesson/types'
import { arcBetween } from '../geometry'
import { useStageMotion } from '../motion'
import { ARROW_HEAD_D, arrowHeadTransform } from './markGeometry'
import type { Geometry } from './useLayerGeometry'

const FLOW_BULGE = 0.12

export function FlowArrow({
  mark,
  geometry,
}: {
  mark: Extract<Mark, { kind: 'flow' }>
  geometry: Geometry
}) {
  const { tr, off } = useStageMotion()
  const a = geometry.get(mark.from)
  const b = geometry.get(mark.to)
  if (!a || !b) return null
  const arc = arcBetween(a, b, FLOW_BULGE)
  const draw = tr('draw')
  const headIn = {
    ...tr('enter'),
    delay: typeof draw.duration === 'number' ? draw.duration * 0.8 : 0,
  }
  const both = mark.both === true
  return (
    <motion.g
      data-mark={mark.id}
      data-mark-kind="flow"
      data-from={mark.from}
      data-to={mark.to}
      data-both={both ? 'true' : 'false'}
      style={{ opacity: 0.7 }}
      exit={{ opacity: 0, transition: tr('exit') }}
    >
      <motion.path
        d={arc.d}
        fill="none"
        stroke="var(--accent)"
        strokeWidth={1.5}
        strokeLinecap="round"
        initial={off ? false : { pathLength: 0 }}
        animate={{ pathLength: 1 }}
        transition={draw}
      />
      <motion.path
        data-arrow-head="end"
        d={ARROW_HEAD_D}
        transform={arrowHeadTransform(arc, 'end')}
        fill="var(--accent)"
        initial={off ? false : { opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={headIn}
      />
      {both ? (
        <motion.path
          data-arrow-head="start"
          d={ARROW_HEAD_D}
          transform={arrowHeadTransform(arc, 'start')}
          fill="var(--accent)"
          initial={off ? false : { opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ ...tr('enter'), delay: 0 }}
        />
      ) : null}
    </motion.g>
  )
}
