/**
 * II.6 — G-Set. A set you can only add to; merge is union, so the three laws come for free.
 * Scenes: `union` (adds from three sides, merged in a ring), `no-remove` (the operation that does
 * not exist), `acks` (in context: an announcement with an LWW title and a G-Set of acks).
 */
import {
  topic,
  scene,
  step,
  alice,
  bob,
  carol,
  server,
  note,
  highlight,
  callout,
  cross,
  clearMarks,
  same,
  tick,
  offline,
  online,
  crdt,
  gset,
  doc,
  seed,
  S,
  merge,
  syncAll,
  expect,
} from '@/lesson/builders'

export default topic({
  id: 'g-set',
  title: 'G-Set',
  goal: 'Learn when a G-Set fits data that is only ever added, and why union needs no extra bookkeeping.',
  whenToUse: [
    'Things that are only ever added: message ids you have seen, peers you have met, events.',
    'Questions of the form "has this ever happened?".',
    'You want the simplest possible set, and delete is truly never needed.',
  ],
  whenNotToUse: [
    'Anything that must be removable (2P-Set, LWW-Element-Set, OR-Set).',
    'The set grows without bound and memory matters: a G-Set never shrinks.',
    'Membership means "currently true" rather than "happened once".',
  ],
  realWorld:
    'Seen-message ids for de-duplication; the peers a node knows; who has acknowledged an announcement.',
  scenes: [
    scene('union', { layout: 'triangle', actors: [alice(), bob(), carol()] }, [
      step(
        's01',
        'A **G-Set** is a set you can only add to. The merge rule is **union**: keep everything either side has.',
        crdt.init(['alice', 'bob', 'carol'], 'seen', 'g-set'),
        note('rule', 'merge = union · the only operation is add · nothing ever leaves'),
      ),
      step(
        's02',
        'Each node has seen some message ids: Alice m1 and m2, Bob m2 and m3, Carol m4.',
        gset('seen').add('alice', 'm1'),
        gset('seen').add('alice', 'm2'),
        gset('seen').add('bob', 'm2'),
        gset('seen').add('bob', 'm3'),
        gset('seen').add('carol', 'm4'),
        expect('alice.seen', ['m1', 'm2']),
        expect('bob.seen', ['m2', 'm3']),
        expect('carol.seen', ['m4']),
      ),
      step(
        's03',
        'Alice sends her whole state to Bob.',
        crdt.send('alice', 'bob', 'seen', { id: 'x1' }),
      ),
      step(
        's04',
        'Bob merges: the union is m1, m2, m3. Both sides had m2, so it appears once.',
        merge('x1'),
        highlight('bob.seen[m2]'),
        expect('bob.seen', ['m1', 'm2', 'm3']),
      ),
      step(
        's05',
        'Bob sends to Carol, and Carol sends on to Alice. Each merge is a union again.',
        crdt.send('bob', 'carol', 'seen', { id: 'x2' }),
        merge('x2'),
        crdt.send('carol', 'alice', 'seen', { id: 'x3' }),
        merge('x3'),
        expect('carol.seen', ['m1', 'm2', 'm3', 'm4']),
        expect('alice.seen', ['m1', 'm2', 'm3', 'm4']),
      ),
      step(
        's06',
        'Alice and Carol already agree. Bob is one step behind: nobody has told him about m4 yet.',
        same('alice.seen', 'carol.seen'),
        highlight('bob.seen', { tone: 'info' }),
        expect('bob.seen', ['m1', 'm2', 'm3']),
      ),
      step(
        's07',
        'Alice sends to Bob once more. Now all three hold m1, m2, m3, m4.',
        clearMarks(),
        crdt.send('alice', 'bob', 'seen', { id: 'x4' }),
        merge('x4'),
        same('alice.seen', 'bob.seen', 'carol.seen'),
        expect('bob.seen', ['m1', 'm2', 'm3', 'm4']),
      ),
      step(
        's08',
        'Carol got m1 through Bob, and Bob got m4 through Alice. The states went round in a ring; order and grouping did not matter.',
        highlight(['carol.seen[m1]', 'bob.seen[m4]'], { tone: 'ok' }),
      ),
      step.long(
        's09',
        'Union is commutative, associative and idempotent by nature. A G-Set gets the three laws for free, with no sidecar at all.',
      ),
    ]),
    scene('no-remove', { layout: 'pair', actors: [alice(), bob()] }, [
      step(
        's01',
        'A task has two tags, kept as a G-Set: draft and urgent. Both copies agree.',
        crdt.init(['alice', 'bob'], 'tags', 'g-set'),
        gset('tags').add('alice', 'draft'),
        gset('tags').add('alice', 'urgent'),
        crdt.sync('alice', 'bob', 'tags'),
        same('alice.tags', 'bob.tags'),
        expect('bob.tags', ['draft', 'urgent']),
      ),
      step(
        's02',
        'The task ships. Alice wants to remove draft.',
        clearMarks(),
        highlight('alice.tags[draft]'),
      ),
      step(
        's03',
        'Whoops — a G-Set has no remove. The only operation is add.',
        cross('alice.tags[draft]'),
        callout('alice.tags', 'no remove operation', { tone: 'warn' }),
      ),
      step(
        's04',
        'Even if her app hid draft on her screen, Bob still holds it. The next merge is a union, and union would bring it right back.',
        clearMarks(),
        callout('bob.tags[draft]', 'would come back on merge', { tone: 'warn' }),
      ),
      step(
        's05',
        'Bob syncs with Alice anyway. Both copies still show draft: no G-Set state can say that a tag is gone.',
        clearMarks(),
        crdt.sync('alice', 'bob', 'tags'),
        same('alice.tags', 'bob.tags'),
        expect('alice.tags', ['draft', 'urgent']),
      ),
      step.long(
        's06',
        'If you need remove, you need more sidecar: a tombstone, a timestamp, or a tag. That is the next three topics.',
      ),
    ]),
    scene(
      'acks',
      {
        layout: 'hub',
        clock: { show: true },
        actors: [
          server('Relay'),
          alice({ icon: 'phone' }),
          bob({ icon: 'laptop' }),
          carol({ icon: 'phone' }),
        ],
      },
      [
        step(
          's01',
          'In context: an announcement. The title is an **LWW register**; the people who acknowledged it are a G-Set.',
          crdt.doc(
            ['server', 'alice', 'bob', 'carol'],
            'post',
            { title: S.lww(), acked: S.gset() },
            { seed: [seed.at('title', 'set', 'Office closed Fri')] },
          ),
          expect('alice.post.title', 'Office closed Fri'),
        ),
        step(
          's02',
          'Alice taps acknowledge: her name joins acked. Carol is offline; she acknowledges too, and it waits on her phone.',
          doc('post').at('acked').add('alice', 'alice'),
          offline('carol'),
          doc('post').at('acked').add('carol', 'carol'),
          expect('alice.post.acked', ['alice']),
          expect('carol.post.acked', ['carol']),
        ),
        step(
          's03',
          'At t=1 Bob fixes a typo in the title, and acknowledges as well.',
          tick(),
          doc('post').at('title').set('bob', 'Office closed Friday'),
          doc('post').at('acked').add('bob', 'bob'),
          expect('bob.post.title@ts', 1),
          expect('bob.post.acked', ['bob']),
        ),
        step(
          's04',
          'Alice and Bob sync with the relay. The relay now holds the fixed title and two acks.',
          syncAll('post', ['alice', 'server'], ['bob', 'server'], ['alice', 'server']),
          expect('server.post.title', 'Office closed Friday'),
          expect('server.post.acked', ['alice', 'bob']),
          expect('alice.post.acked', ['alice', 'bob']),
        ),
        step(
          's05',
          'Carol comes back online and syncs. Her ack joins the union, and she gets the fixed title.',
          online('carol'),
          crdt.sync('carol', 'server', 'post'),
          highlight('carol.post.acked[carol]'),
          expect('carol.post.acked', ['alice', 'bob', 'carol']),
          expect('carol.post.title', 'Office closed Friday'),
        ),
        step(
          's06',
          'One more round with the relay. Every copy: the fixed title and three acks.',
          clearMarks(),
          syncAll('post', ['alice', 'server'], ['bob', 'server']),
          same('server.post', 'alice.post', 'bob.post', 'carol.post'),
          expect('bob.post.acked', ['alice', 'bob', 'carol']),
        ),
        step.long(
          's07',
          'An ack can never be un-acked by accident. For this data, no remove is a feature, not a gap.',
        ),
      ],
      { inContext: true },
    ),
  ],
})
