/**
 * II.8 — LWW-Element-Set. Per element: newest add stamp, newest remove stamp; the newer decides;
 * a tie goes to the bias. Scenes: `two-times-per-element` (re-add after a concurrent remove),
 * `bias` (the same tie on an add-wins and a remove-wins set, side by side), `follows` (in
 * context: follow, unfollow, follow again across a phone, a laptop and a relay).
 */
import {
  topic,
  scene,
  step,
  alice,
  server,
  device,
  bob,
  note,
  highlight,
  conflict,
  check,
  cross,
  clearMarks,
  same,
  tomb,
  tick,
  offline,
  online,
  crdt,
  lwwSet,
  doc,
  seed,
  S,
  expect,
} from '@/lesson/builders'

export default topic({
  id: 'lww-element-set',
  title: 'LWW-Element-Set',
  goal: 'Pick an LWW-Element-Set when the newest add or remove should win, and choose its bias on purpose.',
  whenToUse: [
    'Add and remove both happen often and the latest intent should win (favorites, follows).',
    'You already have good-enough timestamps, for example because you use LWW elsewhere.',
    'Re-adding after a remove must work.',
  ],
  whenNotToUse: [
    'Concurrent add and remove of one element are common and you want add-wins without clocks.',
    'Device clocks cannot be trusted (Unit IV).',
    'You need remove-only-what-I-saw semantics rather than newest-stamp-wins (OR-Set).',
  ],
  realWorld:
    'Follow and unfollow lists; favorites synced across devices; Cassandra set columns (one timestamp per element; a tie goes to the remove).',
  scenes: [
    scene(
      'two-times-per-element',
      { layout: 'pair', clock: { show: true }, actors: [alice(), bob()] },
      [
        step(
          's01',
          'An **LWW-Element-Set** gives each element two timestamps: its newest add and its newest remove. The newer one decides.',
          crdt.init(['alice', 'bob'], 'fav', 'lww-element-set', { bias: 'add' }),
          note('rule', 'in set if add ts > remove ts · tie → bias (here: add wins)'),
        ),
        step(
          's02',
          'At t=1 Alice favorites jazz; at t=2 Bob favorites rock. Each add is stamped with its time.',
          tick(),
          lwwSet('fav').add('alice', 'jazz'),
          tick(),
          lwwSet('fav').add('bob', 'rock'),
          highlight(['alice.fav[jazz]@addTs', 'bob.fav[rock]@addTs']),
          expect('alice.fav[jazz]@addTs', 1),
          expect('bob.fav[rock]@addTs', 2),
        ),
        step(
          's03',
          'They sync. Both hold jazz (added t=1) and rock (added t=2).',
          crdt.sync('alice', 'bob', 'fav'),
          same('alice.fav', 'bob.fav'),
          expect('alice.fav', ['jazz', 'rock']),
        ),
        step(
          's04',
          'At t=3 Bob removes jazz. Jazz stays in the data with remove stamp t=3, but it is no longer in the set.',
          clearMarks(),
          tick(),
          lwwSet('fav').remove('bob', 'jazz'),
          highlight('bob.fav[jazz]@removeTs', { tone: 'warn' }),
          tomb('bob.fav[jazz]'),
          expect('bob.fav', ['rock']),
          expect('bob.fav[jazz]@removeTs', 3),
        ),
        step(
          's05',
          'At t=4 Alice, who has not seen that, adds jazz again. Her add stamp is now t=4.',
          tick(),
          lwwSet('fav').add('alice', 'jazz'),
          highlight('alice.fav[jazz]@addTs'),
          conflict('alice.fav[jazz]', 'bob.fav[jazz]'),
          expect('alice.fav[jazz]@addTs', 4),
        ),
        step(
          's06',
          'They sync and keep the newest of each stamp per element. Jazz has add t=4 and remove t=3, so jazz is in.',
          clearMarks(),
          crdt.sync('alice', 'bob', 'fav'),
          highlight(['alice.fav[jazz]@addTs', 'alice.fav[jazz]@removeTs']),
          same('alice.fav', 'bob.fav'),
          expect('alice.fav', ['jazz', 'rock']),
          expect('bob.fav[jazz]@addTs', 4),
          expect('bob.fav[jazz]@removeTs', 3),
        ),
        step.long(
          's07',
          'Re-add works, unlike the 2P-Set. The price: two timestamps per element, kept forever, and a clock you can trust.',
        ),
      ],
    ),
    scene('bias', { layout: 'pair', clock: { show: true }, actors: [alice(), bob()] }, [
      step(
        's01',
        'Two sets that both hold pop, one per tie rule: addWins keeps pop on a tie, removeWins drops it. Alice and Bob each hold both.',
        crdt.init(['alice', 'bob'], 'addWins', 'lww-element-set', {
          bias: 'add',
          seed: [seed('add', 'pop')],
        }),
        crdt.init(['alice', 'bob'], 'removeWins', 'lww-element-set', {
          bias: 'remove',
          seed: [seed('add', 'pop')],
        }),
        note('rule', 'addWins: tie → add wins · removeWins: tie → remove wins'),
        expect('alice.addWins', ['pop']),
        expect('bob.removeWins', ['pop']),
      ),
      step(
        's02',
        'At t=1, in both sets at once: Alice adds pop again (a fresh add stamp) and Bob removes pop. Neither has seen the other.',
        tick(),
        lwwSet('addWins').add('alice', 'pop'),
        lwwSet('removeWins').add('alice', 'pop'),
        lwwSet('addWins').remove('bob', 'pop'),
        lwwSet('removeWins').remove('bob', 'pop'),
        conflict('alice.addWins[pop]', 'bob.addWins[pop]'),
        conflict('alice.removeWins[pop]', 'bob.removeWins[pop]'),
        expect('alice.addWins[pop]@addTs', 1),
        expect('bob.addWins[pop]@removeTs', 1),
        expect('bob.addWins', []),
        expect('bob.removeWins', []),
      ),
      step(
        's03',
        'Sync both sets. For pop, add t=1 and remove t=1: the timestamps tie and cannot decide.',
        clearMarks(),
        crdt.sync('alice', 'bob', 'addWins'),
        crdt.sync('alice', 'bob', 'removeWins'),
        highlight(['alice.addWins[pop]@addTs', 'alice.addWins[pop]@removeTs'], { tone: 'warn' }),
        expect('alice.addWins[pop]@addTs', 1),
        expect('alice.addWins[pop]@removeTs', 1),
        expect('alice.removeWins[pop]@addTs', 1),
        expect('alice.removeWins[pop]@removeTs', 1),
      ),
      step(
        's04',
        'addWins: pop is in. The tie went to the add, on both copies.',
        clearMarks(),
        check('alice.addWins[pop]'),
        same('alice.addWins', 'bob.addWins'),
        expect('alice.addWins', ['pop']),
        expect('bob.addWins', ['pop']),
      ),
      step(
        's05',
        'removeWins: pop is out. Same stamps, other **bias**, and again both copies agree: the bias is part of the rule.',
        cross('alice.removeWins[pop]'),
        same('alice.removeWins', 'bob.removeWins'),
        expect('alice.removeWins', []),
        expect('bob.removeWins', []),
      ),
      step.long(
        's06',
        'Pick the bias by cost: is an item wrongly present worse, or an item wrongly missing? Decide once, up front.',
      ),
    ]),
    scene(
      'follows',
      {
        layout: 'hub',
        clock: { show: true },
        actors: [
          server('Relay'),
          alice({ icon: 'phone', subtitle: 'phone' }),
          device('laptop', 'Laptop', { owner: 'alice', icon: 'laptop' }),
        ],
      },
      [
        step(
          's01',
          'In context: a profile. The display name is an LWW register; the accounts Alice follows are an LWW-Element-Set, add-wins.',
          crdt.doc(
            ['server', 'alice', 'laptop'],
            'profile',
            { name: S.lww(), follows: S.lwwSet({ bias: 'add' }) },
            { seed: [seed.at('name', 'set', 'alice')] },
          ),
          expect('laptop.profile.name', 'alice'),
        ),
        step(
          's02',
          'At t=1, on the phone, Alice follows @dan and syncs with the relay.',
          tick(),
          doc('profile').at('follows').add('alice', '@dan'),
          crdt.sync('alice', 'server', 'profile'),
          expect('server.profile.follows', ['@dan']),
          expect('server.profile.follows[@dan]@addTs', 1),
        ),
        step(
          's03',
          'The laptop syncs with the relay and sees @dan. Then the phone goes offline.',
          crdt.sync('laptop', 'server', 'profile'),
          offline('alice'),
          expect('laptop.profile.follows', ['@dan']),
        ),
        step(
          's04',
          'At t=2, on the laptop, she unfollows @dan and renames herself to Alice Lee. The laptop syncs.',
          tick(),
          doc('profile').at('follows').remove('laptop', '@dan'),
          doc('profile').at('name').set('laptop', 'Alice Lee'),
          crdt.sync('laptop', 'server', 'profile'),
          tomb('server.profile.follows[@dan]'),
          expect('server.profile.name', 'Alice Lee'),
          expect('server.profile.follows', []),
          expect('server.profile.follows[@dan]@removeTs', 2),
        ),
        step(
          's05',
          'At t=3 the phone, still offline, taps follow @dan again. Its add stamp is t=3; it has not seen the remove.',
          tick(),
          doc('profile').at('follows').add('alice', '@dan'),
          highlight('alice.profile.follows[@dan]@addTs'),
          conflict('alice.profile.follows[@dan]', 'laptop.profile.follows[@dan]'),
          expect('alice.profile.follows[@dan]@addTs', 3),
        ),
        step(
          's06',
          'The phone reconnects and syncs. For @dan, add t=3 beats remove t=2, so she is following again.',
          clearMarks(),
          online('alice'),
          crdt.sync('alice', 'server', 'profile'),
          highlight([
            'server.profile.follows[@dan]@addTs',
            'server.profile.follows[@dan]@removeTs',
          ]),
          expect('server.profile.follows', ['@dan']),
          expect('alice.profile.name', 'Alice Lee'),
        ),
        step(
          's07',
          'The laptop syncs too, and every copy agrees: name Alice Lee, following @dan. Her last tap won, which is what she meant.',
          crdt.sync('laptop', 'server', 'profile'),
          same('server.profile', 'alice.profile', 'laptop.profile'),
          expect('laptop.profile.follows', ['@dan']),
        ),
        step.long(
          's08',
          'Per element, the newest stamp wins. That only works when the stamps are honest; Unit IV is about making them so.',
        ),
      ],
      { inContext: true },
    ),
  ],
})
