/**
 * II.7 — 2P-Set. An add set plus a removed set (tombstones): present = added and not removed.
 * Scenes: `add-and-remove` (the second set), `no-re-add` (re-add is ignored, and a concurrent
 * add/remove race: the tombstone wins in any order), `revoked-keys` (in context: API keys that
 * must stay dead, next to an LWW plan field).
 */
import {
  topic,
  scene,
  step,
  alice,
  bob,
  carol,
  server,
  service,
  note,
  highlight,
  callout,
  conflict,
  cross,
  clearMarks,
  same,
  tomb,
  tick,
  spawn,
  layout,
  crdt,
  twoPSet,
  doc,
  seed,
  S,
  merge,
  syncAll,
  expect,
} from '@/lesson/builders'

export default topic({
  id: 'two-phase-set',
  title: '2P-Set',
  goal: 'Pick a 2P-Set when a removed element must stay removed, and explain what the tombstone costs you.',
  whenToUse: [
    'Things that must stay gone once removed: revoked keys, banned users, unsubscribed emails.',
    'You want remove with the least sidecar: one tombstone per removed element.',
    'Elements are unique and will never be added again by design.',
  ],
  whenNotToUse: [
    'Users may add, remove, and add again (use an LWW-Element-Set or an OR-Set).',
    'Many removes over time: every tombstone is kept forever.',
    'You want the latest intent to win, not remove to win.',
  ],
  realWorld:
    'API-key revocation lists; do-not-email lists; banned-user sets in a multi-region service.',
  scenes: [
    scene('add-and-remove', { layout: 'pair', actors: [alice(), bob()] }, [
      step(
        's01',
        'A **2P-Set** is two G-Sets: added, and removed. An element is in the set when it is added and not removed.',
        crdt.init(['alice', 'bob'], 'guests', 'two-phase-set'),
        note('rule', 'in set = added and not removed · merge = union of both sets'),
      ),
      step(
        's02',
        'Alice invites Dan and Eve.',
        twoPSet('guests').add('alice', 'dan'),
        twoPSet('guests').add('alice', 'eve'),
        expect('alice.guests', ['dan', 'eve']),
      ),
      step(
        's03',
        'They sync. Bob has both guests.',
        crdt.sync('alice', 'bob', 'guests'),
        same('alice.guests', 'bob.guests'),
        expect('bob.guests', ['dan', 'eve']),
      ),
      step(
        's04',
        'Bob un-invites Dan. Dan is not deleted: his entry gets a **tombstone**, a marker that says removed.',
        clearMarks(),
        twoPSet('guests').remove('bob', 'dan'),
        tomb('bob.guests[dan]'),
        expect('bob.guests', ['eve']),
        expect('bob.guests[dan]@tomb', true),
      ),
      step(
        's05',
        "Bob's set reads as eve. Dan stays in the data, struck through: present in the record, absent from the answer.",
        callout('bob.guests[dan]', 'tombstone', { tone: 'info' }),
      ),
      step(
        's06',
        'Bob sends his whole state to Alice: both G-Sets travel together.',
        clearMarks(),
        crdt.send('bob', 'alice', 'guests', { id: 'm1' }),
      ),
      step(
        's07',
        'Alice merges: union of added, union of removed. Dan is tombstoned on both sides.',
        merge('m1'),
        tomb('alice.guests[dan]'),
        same('alice.guests', 'bob.guests'),
        expect('alice.guests', ['eve']),
        expect('alice.guests[dan]@tomb', true),
      ),
      step.long(
        's08',
        'The tombstone is the sidecar that makes remove safe. Without it, the next union would bring Dan back.',
      ),
    ]),
    scene(
      'no-re-add',
      null,
      [
        step(
          's01',
          'Dan apologizes. Alice invites him again: add dan.',
          twoPSet('guests').add('alice', 'dan'),
          expect('alice.guests', ['eve']),
        ),
        step(
          's02',
          'Whoops — nothing happens: dan is already in added, and his tombstone is in removed, so removed wins.',
          cross('alice.guests[dan]'),
          callout('alice.guests[dan]', 'add ignored: tombstone wins', { tone: 'warn' }),
        ),
        step(
          's03',
          'Now a race. Carol joins with an empty copy and invites Eve; that is her whole state.',
          clearMarks(),
          spawn(carol()),
          layout('triangle'),
          crdt.init(['carol'], 'guests', 'two-phase-set'),
          twoPSet('guests').add('carol', 'eve'),
          expect('carol.guests', ['eve']),
        ),
        step(
          's04',
          'At the same time Bob un-invites Eve. Two concurrent changes to eve: an add at Carol, a remove at Bob.',
          twoPSet('guests').remove('bob', 'eve'),
          tomb('bob.guests[eve]'),
          conflict('carol.guests[eve]', 'bob.guests[eve]'),
          expect('bob.guests', []),
        ),
        step(
          's05',
          'Bob sends his state to Carol.',
          clearMarks(),
          crdt.send('bob', 'carol', 'guests', { id: 'm2' }),
        ),
        step(
          's06',
          'Carol merges: union of added, union of removed. Eve is tombstoned, so the remove won the race.',
          merge('m2'),
          tomb('carol.guests[eve]'),
          expect('carol.guests', []),
          expect('carol.guests[eve]@tomb', true),
        ),
        step(
          's07',
          'Sync everyone: three copies, no guests, two tombstones. Remove wins in any order — gone is gone.',
          syncAll('guests', ['alice', 'bob'], ['alice', 'carol']),
          note(
            'rule',
            'in set = added and not removed · merge = union of both sets · gone is gone',
          ),
          same('alice.guests', 'bob.guests', 'carol.guests'),
          expect('alice.guests', []),
          expect('alice.guests[eve]@tomb', true),
        ),
        step.long(
          's08',
          'Good for revoked keys and banned users, bad for a shopping list. Pick a set by what remove should mean.',
        ),
      ],
      { startFrom: 'add-and-remove' },
    ),
    scene(
      'revoked-keys',
      {
        layout: 'hub',
        clock: { show: true },
        actors: [server('Auth US'), service('eu', 'Auth EU', 'a'), service('ap', 'Auth AP', 'b')],
      },
      [
        step(
          's01',
          'In context: three auth servers share one customer record. The plan is an LWW register; the active API keys are a 2P-Set.',
          crdt.doc(
            ['server', 'eu', 'ap'],
            'acct',
            { plan: S.lww(), keys: S.twoP() },
            { seed: [seed.at('plan', 'set', 'Free')] },
          ),
          expect('server.acct.plan', 'Free'),
        ),
        step(
          's02',
          'EU issues key k1 and AP issues key k2. Both sync with US.',
          doc('acct').at('keys').add('eu', 'k1'),
          doc('acct').at('keys').add('ap', 'k2'),
          syncAll('acct', ['eu', 'server'], ['ap', 'server']),
          expect('server.acct.keys', ['k1', 'k2']),
          expect('ap.acct.keys', ['k1', 'k2']),
        ),
        step(
          's03',
          'At t=1 the customer upgrades to Pro in EU, and EU syncs with US.',
          tick(),
          doc('acct').at('plan').set('eu', 'Pro'),
          crdt.sync('eu', 'server', 'acct'),
          expect('server.acct.plan', 'Pro'),
          expect('eu.acct.keys', ['k1', 'k2']),
        ),
        step(
          's04',
          'At t=2 key k1 leaks. AP revokes it: k1 gets a tombstone.',
          tick(),
          doc('acct').at('keys').remove('ap', 'k1'),
          tomb('ap.acct.keys[k1]'),
          expect('ap.acct.keys', ['k2']),
        ),
        step(
          's05',
          'Meanwhile EU, which has not seen the revoke, re-adds k1 from an old cache. Nothing changes there: k1 was still in its added set.',
          doc('acct').at('keys').add('eu', 'k1'),
          highlight('eu.acct.keys[k1]'),
          conflict('eu.acct.keys[k1]', 'ap.acct.keys[k1]'),
          expect('eu.acct.keys', ['k1', 'k2']),
        ),
        step(
          's06',
          'AP and EU sync with US. The tombstone reaches EU: k1 is struck through, and no add can revive it.',
          clearMarks(),
          syncAll('acct', ['ap', 'server'], ['eu', 'server']),
          tomb('eu.acct.keys[k1]'),
          cross('eu.acct.keys[k1]'),
          expect('eu.acct.keys', ['k2']),
          expect('eu.acct.keys[k1]@tomb', true),
        ),
        step(
          's07',
          'Every region agrees: plan Pro, keys k2, and k1 dead for good.',
          clearMarks(),
          same('server.acct', 'eu.acct', 'ap.acct'),
          expect('ap.acct.plan', 'Pro'),
          expect('server.acct.keys', ['k2']),
        ),
        step.long(
          's08',
          'A revoked key that came back would be a security hole. Here, no re-add is exactly the guarantee you want.',
        ),
      ],
      { inContext: true },
    ),
  ],
})
