/**
 * Build-time SEO/agent artifacts (docs/architecture.md "SEO"): loads the real catalog + lesson
 * content through Vite's SSR module loader and writes into public/ (git-ignored; regenerated by
 * `pnpm build`):
 *   sitemap.xml    — every English page (en is the canonical locale until translations land)
 *   llms.txt       — the llms.txt convention: a markdown map of the site for agents
 *   llms-full.txt  — the whole course as plain text: goal, rules, every step's narration,
 *                    when to use / when not to use / real world, per topic
 * Most AI crawlers do not execute JavaScript, so these files ARE the site for them.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
import { createServer } from 'vite'

const SITE_URL = process.env.SITE_URL ?? 'https://learn.hamptonmakes.com'
const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const today = new Date().toISOString().slice(0, 10)

const server = await createServer({
  root,
  logLevel: 'error',
  server: { middlewareMode: true },
  optimizeDeps: { noDiscovery: true },
})

try {
  const { modules } = await server.ssrLoadModule('/src/content/catalog.ts')
  const { topicLoaders, topicKeyOf } = await server.ssrLoadModule('/src/content/registry.ts')

  /** say-markup → plain text: **term** → term, [text](/path) → text, `code` stays backticked. */
  const plain = (say) =>
    say.replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\[([^\]]+)\]\(\/[^)\s]*\)/g, '$1')

  const pages = [`${SITE_URL}/en`]
  const llms = []
  const full = []

  llms.push(
    `# Hampton's CS Concept Lab`,
    ``,
    `> Animated, step-by-step lessons on the computer science ideas working programmers usually skip — starting with CRDTs. Every value on screen is computed by real implementations; lessons are data driving real code. Free and open source: https://github.com/HamptonMakes/learning-lab`,
    ``,
    `The full text of every lesson is in /llms-full.txt. Pages are client-rendered; these files are the crawlable form.`,
    ``,
  )
  full.push(
    `# Hampton's CS Concept Lab — the full course as text`,
    ``,
    `Site: ${SITE_URL} · Source: https://github.com/HamptonMakes/learning-lab`,
    `Lessons are step-by-step and animated on the site; below is every step's narration in order.`,
    ``,
  )

  for (const m of modules) {
    if (m.status === 'coming-soon') continue
    const suffix = m.status === 'prototype' ? ' (prototype)' : ''
    pages.push(`${SITE_URL}/en/${m.id}`)
    llms.push(`## ${m.title}${suffix}`, ``, `${m.summary}`, ``)
    full.push(`\n# Module: ${m.title}${suffix}`, ``, m.summary, ``)
    for (const u of m.units) {
      llms.push(`### ${u.numeral} · ${u.title}`, ``)
      full.push(`\n## Unit ${u.numeral} — ${u.title}`, ``, u.summary ?? '', ``)
      for (const t of u.topics) {
        const key = topicKeyOf(m.id, u.id, t.id)
        const loader = topicLoaders[key]
        if (!loader) continue
        const url = `${SITE_URL}/en/${m.id}/${u.id}/${t.id}`
        pages.push(url)
        llms.push(`- [${t.title}](${url}): ${t.summary}`)
        const topic = (await loader()).default
        full.push(`\n### ${t.title}`, ``, `${t.summary} (${url})`, ``)
        if (topic.goal) full.push(`Goal: ${plain(topic.goal)}`, ``)
        if (topic.rules?.length) {
          full.push(`How it works:`)
          for (const r of topic.rules) full.push(`- ${plain(r)}`)
          full.push(``)
        }
        for (const scene of topic.scenes) {
          if (scene.title) full.push(`Scene: ${scene.title}`, ``)
          for (const step of scene.steps) full.push(plain(step.say))
          full.push(``)
        }
        if (topic.whenToUse?.length) {
          full.push(`When to use it:`)
          for (const w of topic.whenToUse) full.push(`- ${plain(w)}`)
        }
        if (topic.whenNotToUse?.length) {
          full.push(`When not to use it:`)
          for (const w of topic.whenNotToUse) full.push(`- ${plain(w)}`)
        }
        if (topic.realWorld) full.push(`In the real world: ${plain(topic.realWorld)}`)
        full.push(``)
      }
      llms.push(``)
    }
  }

  llms.push(
    `## About`,
    ``,
    `- Author: Hampton Lintorn-Catlin (https://hamptonmakes.com)`,
    `- Source & issues: https://github.com/HamptonMakes/learning-lab`,
    ``,
  )

  const sitemap = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
    ...pages.map((u) => `  <url><loc>${u}</loc><lastmod>${today}</lastmod></url>`),
    `</urlset>`,
    ``,
  ].join('\n')

  writeFileSync(resolve(root, 'public/sitemap.xml'), sitemap)
  writeFileSync(resolve(root, 'public/llms.txt'), llms.join('\n'))
  writeFileSync(resolve(root, 'public/llms-full.txt'), full.join('\n'))
  console.log(
    `seo: sitemap.xml (${pages.length} urls), llms.txt, llms-full.txt (${full.join('\n').length} chars)`,
  )
} finally {
  await server.close()
}
