/**
 * Regex I.2 — Backtracking. The real VM in src/regex/ drives every frame (`regex.init` +
 * `regex.advance`); the lesson narrates the choice points, give-backs and try counts it shows and
 * pins them with `expect`. Scene 3 (in context) races a nested quantifier against a plain one.
 */
import {
  topic,
  scene,
  step,
  device,
  regex,
  note,
  highlight,
  callout,
  check,
  cross,
  clearMarks,
  good,
  expect,
} from '@/lesson/builders'

const matcher = () => device('matcher', 'Matcher', { icon: 'service' })
const M = 'matcher'

export default topic({
  id: 'backtracking',
  title: 'Backtracking',
  goal: 'Watch a greedy test take too much and give characters back one at a time, and spot the patterns that backtrack too much.',
  whenToUse: [
    'Short lines with a fixed tail: key=.* on a config line.',
    'Lazy .*? for the shortest span between two markers.',
    'Anchored patterns (^...$) on input you control.',
  ],
  whenNotToUse: [
    'Nested quantifiers like (a+)+ on untrusted input: exponential backtracking.',
    '.* where a class says what you mean: [^"]* or \\d+.',
    'A regex in a hot path without a timeout or a linear-time engine (RE2, Go, Rust regex).',
  ],
  realWorld:
    "Cloudflare's 2019 outage: a firewall regex ending in .*.*=.* backtracked so hard it took the network down for 27 minutes.",
  scenes: [
    scene('greedy-then-give-back', { layout: 'row', actors: [matcher()] }, [
      step(
        's01',
        'Pattern `a.*b`: an a, then `.*` (any character, as many as possible), then a b. Text: "aXbYb".',
        regex.init(M, 'a.*b', 'aXbYb'),
        expect(`${M}.pattern`, 'a.*b'),
        expect(`${M}.text`, 'aXbYb'),
      ),
      step(
        's02',
        'Position 0 is an a. Pass: cursor 1.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 1),
        expect(`${M}.tries`, 1),
      ),
      step(
        's03',
        '`.*` is **greedy**: it takes as much as it can. First the X: its run, the span it holds, is 1 character, and a **choice point** c1 remembers that.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 2),
        expect(`${M}.stack`, ['p1 @ 1 ×1']),
        expect(`${M}.tries`, 2),
      ),
      step(
        's04',
        'Then b, Y, b. The run holds 4 and the cursor is at the end of the text, position 5.',
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 5),
        expect(`${M}.stack`, ['p1 @ 1 ×4']),
        expect(`${M}.tries`, 5),
      ),
      step(
        's05',
        'The run asks for one more and finds no character left; that is a test, not a failure. The pattern moves on to b: 6 tries.',
        regex.advance(M, 'step'),
        expect(`${M}.pattern@cursor`, 2),
        expect(`${M}.text@cursor`, 5),
        expect(`${M}.tries`, 6),
      ),
      step(
        's06',
        'Test b at position 5: nothing there. Fail, 7 tries.',
        regex.advance(M, 'step'),
        cross(`${M}.pattern[p2]`),
        expect(`${M}.text@cursor`, 5),
        expect(`${M}.tries`, 7),
      ),
      step(
        's07',
        '**Backtracking**: back to c1, the run gives one character back (now 3), and b is tested at position 4: a b. Match, 0 to 5, 8 tries.',
        regex.advance(M, 'step'),
        check(`${M}.text`),
        expect(`${M}.stack`, ['p1 @ 1 ×3']),
        expect(`${M}.text@cursor`, 5),
        expect(`${M}.tries`, 8),
      ),
      step(
        's08',
        'Note which b it matched: the last one. Greedy means the longest span that works, not the first b it could have stopped at.',
        highlight(`${M}.text[2..3]`, { tone: 'warn' }),
        expect(`${M}.text[2..3]`, 'b'),
      ),
      step(
        's09',
        'The **lazy** form `a.*?b` takes as little as it can. Reset: a passes, `.*?` takes nothing, and b is tested at position 1, an X: fail.',
        regex.init(M, 'a.*?b', 'aXbYb'),
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        expect(`${M}.pattern`, 'a.*?b'),
        expect(`${M}.text@cursor`, 1),
        expect(`${M}.stack`, ['p1 @ 1 ×0']),
        expect(`${M}.tries`, 2),
      ),
      step(
        's10',
        'Backtrack: the lazy run grows by one (the X), and b is tested at position 2: a b. Match, 0 to 3, the first b, in 4 tries.',
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        check(`${M}.text`),
        expect(`${M}.text@cursor`, 3),
        expect(`${M}.stack`, ['p1 @ 1 ×1']),
        expect(`${M}.tries`, 4),
      ),
      step.long(
        's11',
        'Both are correct; they answer different questions: the longest span, or the shortest. Every give-back is one more try.',
        callout(`${M}.tries`, 'greedy 8 · lazy 4', { tone: 'info', sticky: true }),
      ),
    ]),
    scene('which-branch', { layout: 'row', actors: [matcher()] }, [
      step(
        's01',
        'Alternation is a choice too: in `(a|ab)c`, group 1 is a or ab, then a c. Text: "abc".',
        regex.init(M, '(a|ab)c', 'abc'),
        expect(`${M}.pattern`, '(a|ab)c'),
        expect(`${M}.text`, 'abc'),
        expect(`${M}.captures.$1`, null),
      ),
      step(
        's02',
        'The engine takes the first branch, a, and saves choice point c1: the other branch, from position 0. The a passes and $1 is a.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 1),
        expect(`${M}.stack`, ['p2 @ 0']),
        expect(`${M}.captures.$1`, 'a'),
        expect(`${M}.tries`, 1),
      ),
      step(
        's03',
        'Now c, at position 1: it is a b. Fail, 2 tries.',
        regex.advance(M, 'step'),
        cross(`${M}.pattern[p6]`),
        expect(`${M}.text@cursor`, 1),
        expect(`${M}.tries`, 2),
      ),
      step(
        's04',
        'Backtrack: pop c1 and take the other branch from position 0. Its a passes; the group is open again, so $1 is empty.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 1),
        expect(`${M}.pattern@cursor`, 4),
        expect(`${M}.stack`, []),
        expect(`${M}.captures.$1`, null),
        expect(`${M}.tries`, 3),
      ),
      step(
        's05',
        'Then b, at position 1: pass. Group 1 closes, and $1 is ab.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 2),
        expect(`${M}.captures.$1`, 'ab'),
        expect(`${M}.tries`, 4),
      ),
      step(
        's06',
        'Then c, at position 2: pass. Match, 0 to 3, with $1 = ab, after 5 tries.',
        regex.advance(M, 'step'),
        check(`${M}.text`),
        expect(`${M}.text@cursor`, 3),
        expect(`${M}.captures.$1`, 'ab'),
        expect(`${M}.tries`, 5),
      ),
      step.long(
        's07',
        'Each `|` and each quantifier is a place the engine may come back to. A few are cheap; many of them, nested, are not.',
        highlight(`${M}.pattern[p2]`),
      ),
    ]),
    scene(
      'blow-up',
      {
        layout: 'pair',
        actors: [
          device('nested', 'Nested', { icon: 'service' }),
          device('plain', 'Plain', { icon: 'service' }),
        ],
      },
      [
        step(
          's01',
          'Pattern `(a+)+b` on "aaaX" looks harmless: some a, then a b. But the inner `a+` sits inside an outer `+`: two quantifiers on the same characters.',
          regex.init('nested', '(a+)+b', 'aaaX'),
          expect('nested.pattern', '(a+)+b'),
          expect('nested.text', 'aaaX'),
        ),
        step(
          's02',
          'Run it to the end: no match, and the tries meter reads 38. The engine tried every way to split aaa between the two pluses, then every later start.',
          regex.advance('nested', 'end'),
          cross('nested.text'),
          expect('nested.tries', 38),
          expect('nested.text@cursor', 4),
        ),
        step(
          's03',
          'Same text, the plain pattern `a+b`: one quantifier. Run to the end: no match after 17 tries.',
          regex.init('plain', 'a+b', 'aaaX'),
          regex.advance('plain', 'end'),
          cross('plain.text'),
          expect('plain.pattern', 'a+b'),
          expect('plain.tries', 17),
        ),
        step(
          's04',
          'One more a, "aaaaX": nested 84 tries, plain 26.',
          regex.init('nested', '(a+)+b', 'aaaaX'),
          regex.advance('nested', 'end'),
          regex.init('plain', 'a+b', 'aaaaX'),
          regex.advance('plain', 'end'),
          highlight('nested.tries', { tone: 'danger' }),
          good('plain.tries'),
          expect('nested.tries', 84),
          expect('plain.tries', 26),
        ),
        step(
          's05',
          'Two more a, "aaaaaaX": nested 368 tries, plain 50. Each extra a about doubles the nested count; the plain count grows by a handful.',
          regex.init('nested', '(a+)+b', 'aaaaaaX'),
          regex.advance('nested', 'end'),
          regex.init('plain', 'a+b', 'aaaaaaX'),
          regex.advance('plain', 'end'),
          highlight('nested.tries', { tone: 'danger' }),
          good('plain.tries'),
          expect('nested.tries', 368),
          expect('plain.tries', 50),
        ),
        step(
          's06',
          'With 30 a characters in a row, the nested pattern needs about a billion tries (simplified). On a busy server, that is an outage.',
          callout('nested.pattern', '2^n tries', { tone: 'danger', sticky: true }),
        ),
        step(
          's07',
          'Real outage: Cloudflare, 2019. One firewall rule ending in `.*.*=.*` pinned CPUs across the whole network for 27 minutes.',
          callout('nested', 'Cloudflare 2019: .*.*=.* · 27 min', { tone: 'warn', sticky: true }),
        ),
        step(
          's08',
          'The fix: say what you mean. One quantifier per run of text, a class instead of `.*` (`[^"]*` cannot run past a quote), and anchors.',
          clearMarks(),
          note('fixes', 'one quantifier per run · [^"]* not .* · anchor with ^ and $', {
            label: 'fixes',
            tone: 'ok',
          }),
          good('plain.pattern'),
        ),
        step.long(
          's09',
          'Or use an engine that never backtracks (RE2, Go, Rust regex): no blow-ups, but no backreferences. Rule: no nested quantifiers on untrusted input.',
          check('plain.pattern'),
          cross('nested.pattern'),
        ),
      ],
      { inContext: true },
    ),
  ],
})
