/**
 * Regex I.1 — Step-by-step matching. The real backtracking VM in src/regex/ drives every frame:
 * the lesson only `regex.init`s a pattern and `regex.advance`s it one event at a time, and pins
 * the cursors and try counts it narrates with `expect`. Patterns are tiny on purpose.
 */
import { topic, scene, step, device, regex, check, cross, expect } from '@/lesson/builders'

const matcher = () => device('matcher', 'Matcher', { icon: 'service' })
const M = 'matcher'

export default topic({
  id: 'step-by-step-matching',
  title: 'Step-by-step matching',
  goal: 'See a regex as a list of small tests run left to right with a cursor, and recognize a match, a failed start and a restart.',
  whenToUse: [
    'Validating or pulling out text with a fixed shape: ids, dates, codes, log fields.',
    'Search and replace in editors and scripts.',
    'Splitting a simple format into tokens before a real parser.',
  ],
  whenNotToUse: [
    'Nested structures (HTML, JSON, code): use a parser.',
    'Free text people type (names, full email rules): be loose, or use a library.',
    'Hot paths over untrusted input before you know how backtracking blows up (next topic).',
  ],
  realWorld: 'Pulling ORD-0042 out of a log line; validating a form field; grep in your terminal.',
  scenes: [
    scene('tests-in-a-row', { layout: 'row', actors: [matcher()] }, [
      step(
        's01',
        'The pattern `cat` is three tests in a row: a c, then an a, then a t. The text is "the cat sat".',
        regex.init(M, 'cat', 'the cat sat'),
        expect(`${M}.pattern`, 'cat'),
        expect(`${M}.text`, 'the cat sat'),
        expect(`${M}.text@cursor`, 0),
        expect(`${M}.tries`, 0),
      ),
      step(
        's02',
        'Start at position 0: test 1 wants a c and sees a t, so it fails. The tries meter counts every character test: 1.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 0),
        expect(`${M}.tries`, 1),
      ),
      step(
        's03',
        'A fail means: move the start one to the right and try again. Position 1 is an h: fail, tries 2.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 1),
        expect(`${M}.tries`, 2),
      ),
      step(
        's04',
        'Position 2 (an e) and position 3 (a space) fail too. Four starts, four red marks, 4 tries.',
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 3),
        expect(`${M}.tries`, 4),
      ),
      step(
        's05',
        'Position 4 is a c. Test 1 passes, and both cursors move: the text cursor to 5, the pattern cursor to the a.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 5),
        expect(`${M}.pattern@cursor`, 1),
        expect(`${M}.tries`, 5),
      ),
      step(
        's06',
        'Test 2 wants an a and sees an a. Pass: cursor 6, and the pattern cursor moves to the t.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 6),
        expect(`${M}.pattern@cursor`, 2),
        expect(`${M}.tries`, 6),
      ),
      step(
        's07',
        'Test 3 wants a t and sees a t. Every test passed: a match from 4 to 7, after 7 tries.',
        regex.advance(M, 'step'),
        check(`${M}.text`),
        expect(`${M}.text@cursor`, 7),
        expect(`${M}.pattern@cursor`, 3),
        expect(`${M}.tries`, 7),
      ),
      step.long(
        's08',
        'That is the whole idea: a cursor in the text, a cursor in the pattern, one test per step, and a restart on fail.',
        expect(`${M}.tries`, 7),
      ),
    ]),
    scene('optional', { layout: 'row', actors: [matcher()] }, [
      step(
        's01',
        'A test can be optional: `colou?r` is six tests, and the fifth, `u?`, means a u or nothing. Text: "colour".',
        regex.init(M, 'colou?r', 'colour'),
        expect(`${M}.pattern`, 'colou?r'),
        expect(`${M}.text`, 'colour'),
      ),
      step(
        's02',
        'c, o, l, o: four tests, four passes. Cursor at 4, 4 tries.',
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 4),
        expect(`${M}.pattern@cursor`, 4),
        expect(`${M}.tries`, 4),
      ),
      step(
        's03',
        'Test 5, `u?`, sees a u and takes it: cursor 5. The engine also saves a **choice point**, c1: it could give that u back later.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 5),
        expect(`${M}.pattern@cursor`, 5),
        expect(`${M}.stack`, ['p4 @ 4 ×1']),
        expect(`${M}.tries`, 5),
      ),
      step(
        's04',
        'Test 6 wants an r and sees an r. Match, 0 to 6, in 6 tries; the choice point was never needed.',
        regex.advance(M, 'step'),
        check(`${M}.text`),
        expect(`${M}.text@cursor`, 6),
        expect(`${M}.tries`, 6),
      ),
      step(
        's05',
        'Same pattern on "color". c, o, l, o pass again: cursor 4.',
        regex.init(M, 'colou?r', 'color'),
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        regex.advance(M, 'step'),
        expect(`${M}.text`, 'color'),
        expect(`${M}.text@cursor`, 4),
        expect(`${M}.tries`, 4),
      ),
      step(
        's06',
        '`u?` sees an r, not a u, so it takes nothing and passes anyway: that is what optional means. No choice point this time, cursor still 4.',
        regex.advance(M, 'step'),
        expect(`${M}.text@cursor`, 4),
        expect(`${M}.pattern@cursor`, 5),
        expect(`${M}.stack`, []),
        expect(`${M}.tries`, 5),
      ),
      step(
        's07',
        'Test 6 wants an r and sees an r: match, 0 to 5, in 6 tries. One pattern, two spellings.',
        regex.advance(M, 'step'),
        check(`${M}.text`),
        expect(`${M}.text@cursor`, 5),
        expect(`${M}.tries`, 6),
      ),
      step.long(
        's08',
        'The question mark is a **quantifier**, like plus and star: one test that may take a different number of characters. Each one is a place the engine may come back to.',
        expect(`${M}.pattern`, 'colou?r'),
      ),
    ]),
    scene(
      'order-id',
      { layout: 'row', actors: [matcher()] },
      [
        step(
          's01',
          'A log line, and we want the order number. Pattern `ORD-(\\d{4})`: O, R, D, a dash, then exactly four digits inside a **capture group**.',
          regex.init(M, 'ORD-(\\d{4})', '2026-08-22 paid ORD-0042 ok'),
          expect(`${M}.pattern`, 'ORD-(\\d{4})'),
          expect(`${M}.text`, '2026-08-22 paid ORD-0042 ok'),
          expect(`${M}.captures.$1`, null),
        ),
        step(
          's02',
          'Positions 0 to 15 all fail on the first test: none of them is an O. The start slides right one place at a time: 16 tries.',
          ...Array.from({ length: 15 }, () => regex.advance(M, 'attempt')),
          expect(`${M}.tries`, 16),
          expect(`${M}.pattern@cursor`, 0),
        ),
        step(
          's03',
          'Position 16 is an O. Pass: cursor 17, and the pattern cursor moves on to R.',
          regex.advance(M, 'attempt'),
          expect(`${M}.text@cursor`, 17),
          expect(`${M}.pattern@cursor`, 1),
          expect(`${M}.tries`, 17),
        ),
        step(
          's04',
          'R, D and the dash pass one by one. Cursor 20; the pattern cursor is on `\\d{4}`, inside the group.',
          regex.advance(M, 'token'),
          regex.advance(M, 'token'),
          regex.advance(M, 'token'),
          expect(`${M}.text@cursor`, 20),
          expect(`${M}.pattern@cursor`, 5),
          expect(`${M}.tries`, 20),
        ),
        step(
          's05',
          '`\\d{4}` is one test run exactly four times: a digit each time. 0, 0, 4 so far: cursor 23.',
          regex.advance(M, 'step'),
          regex.advance(M, 'step'),
          regex.advance(M, 'step'),
          expect(`${M}.text@cursor`, 23),
          expect(`${M}.tries`, 23),
        ),
        step(
          's06',
          'The fourth digit, 2, passes: a match from 16 to 24. The group captured 0042, so $1 hands you just the number.',
          regex.advance(M, 'step'),
          check(`${M}.captures.$1`),
          expect(`${M}.text@cursor`, 24),
          expect(`${M}.captures.$1`, '0042'),
          expect(`${M}.tries`, 24),
        ),
        step.long(
          's07',
          'A line with no ORD- fails at all 21 starts (0 to 20) and reports no match: 21 tries, then it stops. Next topic: when it does not stop so soon.',
          regex.init(M, 'ORD-\\d{4}', '2026-08-22 refund ok'),
          regex.advance(M, 'end'),
          cross(`${M}.text`),
          expect(`${M}.tries`, 21),
          expect(`${M}.text@cursor`, 20),
        ),
      ],
      { inContext: true },
    ),
  ],
})
