/**
 * III.3 — Op-based counter. Every number on stage is computed by src/crdt/op-counter.ts through
 * the delivery layer: `wire: 'ops'` draws the outbox, `expose: ['applied']` shows the dedupe list,
 * and the retry in `minus-and-repeats` is caught by that list (the counter itself would add the
 * delta again). `team-poll` puts two op-counters in a composed document and catches Carol up with
 * a `crdt.sync mode: 'ops'` state-vector exchange. Storyboard: docs/curriculum/unit-3-4.md §III.3.
 */
import {
  topic,
  scene,
  step,
  alice,
  bob,
  carol,
  duplicate,
  offline,
  online,
  note,
  highlight,
  callout,
  check,
  clearMarks,
  same,
  allSame,
  applyAll,
  crdt,
  opcounter,
  doc,
  S,
  apply,
  expect,
} from '@/lesson/builders'

export default topic({
  id: 'op-counter',
  title: 'Op-based counter',
  goal: 'Build a counter from +1 and −1 ops, explain why arrival order never matters, and why every op must still be applied exactly once.',
  whenToUse: [
    'Likes, votes, view counts, tallies: anything that is a stream of +n / −n events.',
    'Many writers, and nobody needs an instantly exact global number.',
    'You already have op ids and a dedupe check (see Ops instead of state).',
    'Ops are tiny and you do not want to ship a per-node table each time.',
  ],
  whenNotToUse: [
    'Limits and quotas (stock ≥ 0, a balance): a counter cannot refuse; two −1s can cross zero.',
    '"The count right now, everywhere": there is no global now.',
    'Repeats cannot be detected (no op ids): use a state-based G- or PN-Counter instead.',
    'Reset to zero: reset does not commute with +1 and needs a special design.',
  ],
  realWorld:
    'Redis Enterprise Active-Active and Riak counters; emoji reactions and view counts have the same shape, though most apps tally them on one server.',
  scenes: [
    scene(
      'increments-commute',
      {
        layout: 'triangle',
        actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' }), carol({ icon: 'tablet' })],
      },
      [
        step(
          's01',
          'Three devices share a like counter driven by ops. Each op is +1 or −1, and each copy adds what it receives.',
          crdt.init(['alice', 'bob', 'carol'], 'likes', 'op-counter', {
            wire: 'ops',
            expose: ['applied'],
          }),
          note('rule', 'copy += op · any order · each op once'),
          expect('alice.likes', 0),
        ),
        step(
          's02',
          'Alice taps like twice. Her copy says 2, and two ops wait in her outbox: alice:1 and alice:2.',
          opcounter('likes').inc('alice'),
          opcounter('likes').inc('alice'),
          highlight('alice@outbox'),
          expect('alice.likes', 2),
          expect('alice@outbox', ['alice:1', 'alice:2']),
        ),
        step(
          's03',
          'Bob taps once: bob:1.',
          opcounter('likes').inc('bob'),
          highlight('bob@outbox'),
          expect('bob@outbox', ['bob:1']),
        ),
        step(
          's04',
          'Everyone broadcasts. Six small messages are in flight, two per op.',
          crdt.broadcast('alice', 'likes'),
          crdt.broadcast('bob', 'likes'),
        ),
        step(
          's05',
          "Carol gets Bob's op first, then Alice's two. Carol: 3.",
          apply('bob:1@carol'),
          apply('alice:1@carol'),
          apply('alice:2@carol'),
          expect('carol.likes', 3),
        ),
        step(
          's06',
          "Bob already counted his own tap. Alice's two ops land on top: 3.",
          apply('alice:1@bob'),
          apply('alice:2@bob'),
          expect('bob.likes', 3),
        ),
        step(
          's07',
          "Alice counted her two first; Bob's op lands last. Alice: 3.",
          apply('bob:1@alice'),
          expect('alice.likes', 3),
        ),
        step(
          's08',
          'Everyone says 3. The ops arrived in a different order on every copy, and 1 + 1 + 1 is 3 in any order.',
          allSame('likes', ['alice', 'bob', 'carol']),
        ),
        step(
          's09',
          'Each copy also keeps the ids it applied: three each. The counter itself is one number; that **sidecar** list is what makes a repeat harmless.',
          clearMarks(),
          highlight(['alice.likes@applied', 'bob.likes@applied', 'carol.likes@applied'], {
            sticky: true,
          }),
          expect('alice.likes@applied', ['alice:1', 'alice:2', 'bob:1']),
        ),
        step.long(
          's10',
          'A counter needs each op once, and nothing else. It never cares about order, because every +1 commutes with every other.',
        ),
      ],
    ),
    scene(
      'minus-and-repeats',
      { layout: 'pair', actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' })] },
      [
        step(
          's01',
          'A like can be undone. The op is −1, and it commutes with every +1 just the same.',
          crdt.init(['alice', 'bob'], 'likes', 'op-counter', { wire: 'ops', expose: ['applied'] }),
          note('rule', 'copy += op · any order · each op once'),
        ),
        step(
          's02',
          'Alice likes (alice:1) and Bob likes (bob:1). Both broadcast, both apply: 2 everywhere.',
          opcounter('likes').inc('alice'),
          opcounter('likes').inc('bob'),
          crdt.broadcast('alice', 'likes'),
          crdt.broadcast('bob', 'likes'),
          apply('alice:1@bob'),
          apply('bob:1@alice'),
          expect('alice.likes', 2),
          expect('bob.likes', 2),
        ),
        step(
          's03',
          'Alice changes her mind: −1, op alice:2. Her copy says 1, and she broadcasts.',
          opcounter('likes').dec('alice'),
          crdt.broadcast('alice', 'likes'),
          expect('alice.likes', 1),
        ),
        step(
          's04',
          "The network is slow, and Alice's app retries: a second copy of alice:2 takes off.",
          duplicate('alice:2@bob', 'retry'),
        ),
        step(
          's05',
          'The first copy lands, and Bob applies −1 and writes alice:2 in his list. Bob: 1.',
          apply('alice:2@bob'),
          highlight('bob.likes@applied'),
          expect('bob.likes', 1),
          expect('bob.likes@applied', ['bob:1', 'alice:1', 'alice:2']),
        ),
        step(
          's06',
          'The retry lands. alice:2 is already on the list, so the counter never sees it: no change.',
          apply('retry'),
          check('bob.likes'),
          expect('bob.likes', 1),
        ),
        step(
          's07',
          'Without the list, the counter would subtract again and show 0, with no way to notice. Adding a delta twice is not **idempotent**; the list makes a repeat harmless.',
          callout('bob.likes@applied', 'seen it: skip', { tone: 'info', sticky: true }),
        ),
        step(
          's08',
          'Both say 1. Careful: nothing stops a copy from dipping below zero, for a moment or for good.',
          same('alice.likes', 'bob.likes'),
        ),
        step.long(
          's09',
          'A counter cannot enforce a floor or a quota. It only adds what it is told, in any order, once.',
          callout('bob.likes', 'no floor, no quota', { tone: 'warn' }),
        ),
      ],
    ),
    scene(
      'team-poll',
      {
        layout: 'triangle',
        actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' }), carol({ icon: 'tablet' })],
      },
      [
        step(
          's01',
          'A team poll on three devices: a question and two op-based counters in one document. The sidecar shows how far each copy has read.',
          crdt.doc(
            ['alice', 'bob', 'carol'],
            'poll',
            { question: S.const('Lunch?'), pizza: S.opCounter(), sushi: S.opCounter() },
            { wire: 'ops', expose: ['vc'] },
          ),
          note('rule', 'copy += op · any order · each op once'),
        ),
        step(
          's02',
          'Alice votes pizza, Bob votes sushi, Carol votes pizza. Three ops wait in three outboxes.',
          doc('poll').at('pizza').inc('alice'),
          doc('poll').at('sushi').inc('bob'),
          doc('poll').at('pizza').inc('carol'),
          expect('alice.poll.pizza', 1),
          expect('bob.poll.sushi', 1),
          expect('carol.poll.pizza', 1),
        ),
        step(
          's03',
          'Carol boards a plane and goes offline before anything is sent.',
          offline('carol'),
        ),
        step(
          's04',
          'Alice and Bob can still reach each other. Each sends the other its vote, and each applies it: pizza 1, sushi 1.',
          crdt.broadcast('alice', 'poll', { to: ['bob'] }),
          crdt.broadcast('bob', 'poll', { to: ['alice'] }),
          apply('alice:1@bob'),
          apply('bob:1@alice'),
          expect('alice.poll.pizza', 1),
          expect('alice.poll.sushi', 1),
          expect('bob.poll.pizza', 1),
        ),
        step(
          's05',
          'Bob votes pizza again, bob:2, and sends it to Alice: pizza 2 there. Carol still sees pizza 1, sushi 0.',
          doc('poll').at('pizza').inc('bob'),
          crdt.broadcast('bob', 'poll', { to: ['alice'] }),
          apply('bob:2@alice'),
          expect('alice.poll.pizza', 2),
          expect('carol.poll.pizza', 1),
          expect('carol.poll.sushi', 0),
        ),
        step(
          's06',
          'Carol lands. She and Alice compare how far each has read, and each sends only what the other lacks: three ops one way, carol:1 the other.',
          online('carol'),
          crdt.sync('carol', 'alice', 'poll', { mode: 'ops' }),
        ),
        step(
          's07',
          'Carol applies the three ops: pizza 3, sushi 1. Alice applies carol:1: pizza 3.',
          applyAll(['alice:1@carol', 'bob:1@carol', 'bob:2@carol', 'carol:1@alice']),
          expect('carol.poll.pizza', 3),
          expect('carol.poll.sushi', 1),
          expect('alice.poll.pizza', 3),
        ),
        step(
          's08',
          'Carol and Bob compare too. Bob lacks only carol:1; Carol lacks nothing from Bob, so one op flies.',
          crdt.sync('carol', 'bob', 'poll', { mode: 'ops' }),
        ),
        step(
          's09',
          'Bob applies it. Everyone: pizza 3, sushi 1, after three different arrival orders.',
          apply('carol:1@bob'),
          allSame('poll', ['alice', 'bob', 'carol']),
          expect('bob.poll.pizza', 3),
        ),
        step.long(
          's10',
          'Comparing how far each side has read and sending only the gap is how Yjs catches a peer up. Unit IV names that table: a **vector clock**.',
          highlight(['alice.poll@vc', 'bob.poll@vc', 'carol.poll@vc'], { sticky: true }),
        ),
      ],
      { inContext: true },
    ),
  ],
})
