/**
 * III.4 — Op-based OR-Set. The same src/crdt/or-set.ts as Unit II, now driven by ops: every tag
 * on stage is minted by the reducer (`alice:1`…), every remove op carries exactly the tags its
 * author had seen, and the add/remove race in `add-vs-remove-race` is decided by those tags, not
 * by a clock. `shared-playlist` composes an OR-Set of small documents with op-counters inside and
 * shows an op landing on a removed (tombstoned) track. Storyboard: docs/curriculum/unit-3-4.md §III.4.
 */
import {
  topic,
  scene,
  step,
  alice,
  bob,
  carol,
  offline,
  online,
  note,
  highlight,
  callout,
  clearMarks,
  same,
  allSame,
  applyAll,
  tomb,
  crdt,
  seed,
  orSet,
  doc,
  S,
  apply,
  expect,
} from '@/lesson/builders'

const RULE = 'add → new tag · remove → the tags you have seen · in the set = at least one live tag'

export default topic({
  id: 'op-or-set',
  title: 'Op-based OR-Set',
  goal: 'Learn how add and remove ops drive an OR-Set, why a remove means "kill these tags", and who wins when an add and a remove cross.',
  rules: [
    'Every add mints a fresh tag: node + counter, like alice:1. The same word added twice has two tags.',
    'A remove does not delete the word. It kills the tags its author has seen.',
    'An element is in the set while at least one of its tags is alive.',
    'When an add and a remove cross, the add wins: the remover never saw the new tag.',
  ],
  shape: {
    name: 'OR-Set element',
    fields: [
      { key: 'element', example: 'urgent', role: 'value' },
      {
        key: 'tags',
        example: 'alice:1, alice:2',
        note: 'one per add, each alive or dead; a remove kills the ones it names',
      },
    ],
    note: 'In the set = at least one live tag. A dead tag stays as the record of a remove.',
  },
  whenToUse: [
    'Membership people add and remove freely: labels, attendees, collaborators, list items.',
    'Re-add after remove must work (a 2P-Set cannot).',
    '"Add wins" is the right answer when two people disagree at the same moment.',
    'Ops are small: one tag per add, a few tags per remove.',
  ],
  whenNotToUse: [
    'Remove must win (bans, revoked access): a concurrent add would undo it.',
    'You need order: use a sequence (RGA, next topic).',
    'Items have editable fields: compose an OR-Set of ids with a record per id (last scene).',
    'You cannot guarantee causal delivery: a remove may arrive before its add (see Ops instead of state).',
  ],
  realWorld:
    'Riak sets and Redis Enterprise Active-Active sets are OR-Sets; issue labels and shared-album members are the shape they fit.',
  scenes: [
    scene(
      'add-and-remove-by-tag',
      { layout: 'pair', actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' })] },
      [
        step(
          's01',
          'Alice and Bob share the labels on one task: an **OR-Set** driven by ops. Every add mints a tag, and a remove names tags.',
          crdt.init(['alice', 'bob'], 'labels', 'or-set', { wire: 'ops' }),
          note('rule', RULE),
          expect('alice.labels', []),
        ),
        step(
          's02',
          'Alice adds urgent. The op carries a fresh tag: alice:1.',
          orSet('labels').add('alice', 'urgent'),
          highlight('alice@outbox'),
          expect('alice.labels[urgent]@tags', [{ tag: 'alice:1', alive: true }]),
        ),
        step(
          's03',
          'She broadcasts and Bob applies: urgent with tag alice:1 on both.',
          crdt.broadcast('alice', 'labels'),
          apply('alice:1@bob'),
          same('alice.labels', 'bob.labels'),
          expect('bob.labels[urgent]@tags', [{ tag: 'alice:1', alive: true }]),
        ),
        step(
          's04',
          'Bob adds bug, tag bob:1. He broadcasts, and Alice applies.',
          clearMarks(),
          orSet('labels').add('bob', 'bug'),
          crdt.broadcast('bob', 'labels'),
          apply('bob:1@alice'),
          expect('alice.labels', ['bug', 'urgent']),
        ),
        step(
          's05',
          'Every add is unique, even for the same word. Alice adds urgent again: a second tag, alice:2.',
          orSet('labels').add('alice', 'urgent'),
          highlight('alice.labels[urgent]@tags'),
          expect('alice.labels[urgent]@tags', [
            { tag: 'alice:1', alive: true },
            { tag: 'alice:2', alive: true },
          ]),
        ),
        step(
          's06',
          'Broadcast; Bob applies. One word, two adds, two tags on both copies.',
          crdt.broadcast('alice', 'labels'),
          apply('alice:2@bob'),
          highlight('bob.labels[urgent]@tags'),
          expect('bob.labels[urgent]@tags', [
            { tag: 'alice:1', alive: true },
            { tag: 'alice:2', alive: true },
          ]),
        ),
        step(
          's07',
          'Bob removes urgent. His op does not say delete the word; it lists the tags he has seen: alice:1, alice:2.',
          clearMarks(),
          orSet('labels').remove('bob', 'urgent'),
          highlight('bob@outbox'),
          tomb('bob.labels[urgent]'),
          expect('bob.labels', ['bug']),
        ),
        step(
          's08',
          'Broadcast; Alice applies. Exactly those two tags die, and urgent is gone on both.',
          crdt.broadcast('bob', 'labels'),
          apply('bob:2@alice'),
          tomb('alice.labels[urgent]'),
          expect('alice.labels', ['bug']),
          expect('alice.labels[urgent]@tags', [
            { tag: 'alice:1', alive: false },
            { tag: 'alice:2', alive: false },
          ]),
        ),
        step(
          's09',
          'Alice adds urgent back: a fresh tag, alice:3. Bob applies it, and urgent is back on both: re-add works, unlike the **2P-Set**.',
          clearMarks(),
          orSet('labels').add('alice', 'urgent'),
          crdt.broadcast('alice', 'labels'),
          apply('alice:3@bob'),
          same('alice.labels', 'bob.labels'),
          expect('bob.labels', ['bug', 'urgent']),
        ),
        step.long(
          's10',
          'A remove never deletes a word. It deletes the tags its author had seen, and that detail is the whole trick.',
          callout('bob.labels', 'remove = kill these tags', { tone: 'info', sticky: true }),
        ),
      ],
    ),
    scene(
      'add-vs-remove-race',
      { layout: 'pair', actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' })] },
      [
        step(
          's01',
          'Both hold eggs with tag bob:1. Now two people act at the same moment.',
          crdt.init(['alice', 'bob'], 'list', 'or-set', {
            wire: 'ops',
            seed: [seed.by('bob', 'add', 'eggs')],
          }),
          note('rule', RULE),
          expect('alice.list[eggs]@tags', [{ tag: 'bob:1', alive: true }]),
        ),
        step(
          's02',
          'Alice removes eggs. Her op kills the one tag she has seen: bob:1.',
          orSet('list').remove('alice', 'eggs'),
          highlight('alice@outbox'),
          tomb('alice.list[eggs]'),
          expect('alice.list', []),
        ),
        step(
          's03',
          'At the same moment Bob adds eggs again: a new tag, bob:2.',
          orSet('list').add('bob', 'eggs'),
          highlight('bob.list[eggs]@tags'),
          expect('bob.list[eggs]@tags', [
            { tag: 'bob:1', alive: true },
            { tag: 'bob:2', alive: true },
          ]),
        ),
        step(
          's04',
          'Both broadcast. The two ops cross in the air.',
          clearMarks(),
          crdt.broadcast('alice', 'list'),
          crdt.broadcast('bob', 'list'),
        ),
        step(
          's05',
          "Bob applies Alice's remove: tag bob:1 dies, but bob:2 lives, so eggs stays.",
          apply('alice:1@bob'),
          highlight('bob.list[eggs]@tags'),
          expect('bob.list', ['eggs']),
          expect('bob.list[eggs]@tags', [
            { tag: 'bob:1', alive: false },
            { tag: 'bob:2', alive: true },
          ]),
        ),
        step(
          's06',
          "Alice applies Bob's add: eggs comes back with tag bob:2.",
          apply('bob:2@alice'),
          highlight('alice.list[eggs]@tags'),
          expect('alice.list', ['eggs']),
        ),
        step(
          's07',
          'Both copies: eggs, live tag bob:2. Add wins, and both agree.',
          clearMarks(),
          same('alice.list', 'bob.list'),
        ),
        step(
          's08',
          "Alice's remove could only kill what Alice had seen, and she never saw bob:2. That is observed remove, with no clock involved.",
          callout('alice.list', 'remove only what you saw', { tone: 'info' }),
        ),
        step.long(
          's09',
          'Add wins is right for labels and shopping lists. It is wrong for bans and revoked access, where remove must win; that needs a different design.',
          callout('bob.list', 'add wins ≠ remove wins', { tone: 'warn', sticky: true }),
        ),
      ],
    ),
    scene(
      'shared-playlist',
      {
        layout: 'triangle',
        actors: [alice({ icon: 'phone' }), bob({ icon: 'phone' }), carol({ icon: 'phone' })],
      },
      [
        step(
          's01',
          'A shared playlist on three phones. Tracks are an OR-Set of small documents; each track has a name and a play counter.',
          crdt.doc(
            ['alice', 'bob', 'carol'],
            'playlist',
            { tracks: S.set(S.map({ name: S.lww(), plays: S.opCounter() })) },
            { wire: 'ops' },
          ),
          note('rule', RULE),
        ),
        step(
          's02',
          'Alice adds Blue Train: a new track whose id is the tag of the add, alice:1. She broadcasts; both apply.',
          doc('playlist').at('tracks').add('alice', { name: 'Blue Train' }),
          crdt.broadcast('alice', 'playlist'),
          apply('alice:1@bob'),
          apply('alice:1@carol'),
          expect('carol.playlist.tracks[alice:1].plays', 0),
        ),
        step(
          's03',
          "Bob plays it twice, Carol once. Each play is a +1 op on that track's counter.",
          doc('playlist').at('tracks[alice:1].plays').inc('bob'),
          doc('playlist').at('tracks[alice:1].plays').inc('bob'),
          doc('playlist').at('tracks[alice:1].plays').inc('carol'),
          expect('bob.playlist.tracks[alice:1].plays', 2),
          expect('carol.playlist.tracks[alice:1].plays', 1),
        ),
        step(
          's04',
          'Broadcast and apply. Everyone: 3 plays.',
          crdt.broadcast('bob', 'playlist'),
          crdt.broadcast('carol', 'playlist'),
          applyAll([
            'bob:1@alice',
            'bob:2@alice',
            'carol:1@alice',
            'bob:1@carol',
            'bob:2@carol',
            'carol:1@bob',
          ]),
          allSame('playlist', ['alice', 'bob', 'carol']),
          expect('alice.playlist.tracks[alice:1].plays', 3),
        ),
        step(
          's05',
          'Bob goes offline and plays it once more: bob:3 waits in his outbox. Meanwhile Alice removes the track, tag alice:1.',
          clearMarks(),
          offline('bob'),
          doc('playlist').at('tracks[alice:1].plays').inc('bob'),
          doc('playlist').at('tracks').remove('alice', 'alice:1'),
          highlight('bob@outbox'),
          tomb('alice.playlist.tracks[alice:1]'),
          expect('bob.playlist.tracks[alice:1].plays', 4),
          expect('alice.playlist.tracks', []),
        ),
        step(
          's06',
          "Alice broadcasts. Carol applies, and the track is gone for her; Bob's copy waits at his door.",
          crdt.broadcast('alice', 'playlist'),
          apply('alice:2@carol'),
          tomb('carol.playlist.tracks[alice:1]'),
          expect('carol.playlist.tracks', []),
        ),
        step(
          's07',
          'Bob comes online and broadcasts his last play. Alice and Carol apply it: the removed track still counts it, and the visible list does not change.',
          online('bob'),
          crdt.broadcast('bob', 'playlist'),
          apply('bob:3@alice'),
          apply('bob:3@carol'),
          expect('alice.playlist.tracks', []),
        ),
        step(
          's08',
          "Bob applies Alice's remove. Gone for Bob too, and all three agree.",
          apply('alice:2@bob'),
          tomb('bob.playlist.tracks[alice:1]'),
          allSame('playlist', ['alice', 'bob', 'carol']),
          expect('bob.playlist.tracks', []),
        ),
        step(
          's09',
          'Carol adds Blue Train again. It is a new element, carol:2, with a new counter: 0 plays.',
          clearMarks(),
          doc('playlist').at('tracks').add('carol', { name: 'Blue Train' }),
          crdt.broadcast('carol', 'playlist'),
          apply('carol:2@alice'),
          apply('carol:2@bob'),
          expect('alice.playlist.tracks[carol:2].plays', 0),
        ),
        step.long(
          's10',
          'Re-add is a fresh start. If the old count must survive, keep a stable track id and use a hidden flag instead: a design choice, not a CRDT law.',
          callout('carol.playlist.tracks[carol:2]', 'new element, new counter', {
            tone: 'info',
            sticky: true,
          }),
        ),
      ],
      { inContext: true },
    ),
  ],
})
