/**
 * III.7 — Tombstones and garbage. `tombstones-pile-up` shows why a delete leaves a marker (a
 * concurrent insert still anchors on it) and how the stored/visible gap grows; `safe-to-collect`
 * proves stability with the version vectors the reducer keeps (`crdt.gc` with `upTo` is refused
 * unless every replica has seen the delete); `collect-too-early` skips the proof (`unsafe`) and a
 * lagging state merge brings the deleted character back. The trailing character is deleted so
 * the resurrection reads cleanly. Storyboard: docs/curriculum/unit-3-4.md §III.7.
 */
import {
  topic,
  scene,
  step,
  alice,
  bob,
  carol,
  offline,
  online,
  note,
  highlight,
  callout,
  compare,
  cross,
  clearMarks,
  same,
  allSame,
  applyAll,
  tomb,
  crdt,
  seed,
  rga,
  apply,
  expect,
} from '@/lesson/builders'

export default topic({
  id: 'tombstones-and-garbage',
  title: 'Tombstones and garbage',
  goal: 'Learn why deletes leave tombstones, what they cost, when one can be collected safely, and what breaks when you collect too early.',
  whenToUse: [
    'Keep a tombstone while any copy may still send an op that points at the dead element.',
    'Collect when every copy has seen the delete: a stability point you can prove.',
    'Give a new device a snapshot without history instead of the full op log.',
    'A "recently deleted" bin in the product is a tombstone with a face.',
  ],
  whenNotToUse: [
    'Do not collect on a timer alone: a copy offline longer than the timer brings data back.',
    'Do not collect without knowing how far every copy has read.',
    'Do not show tombstones in the UI or count them as items.',
    'Every type pays somewhere: OR-Set dead tags, LWW-map removed keys, RGA and 2P-Set tombstones.',
  ],
  realWorld:
    'Cassandra tombstones and zombie rows (gc_grace_seconds); Yjs and Automerge compaction; the Recently Deleted folder in Apple Notes.',
  scenes: [
    scene(
      'tombstones-pile-up',
      { layout: 'pair', actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' })] },
      [
        step(
          's01',
          'A short text: cat. The **sidecar** counts what each copy stores and what it shows: 3 stored, 3 visible.',
          crdt.init(['alice', 'bob'], 'text', 'rga', {
            wire: 'ops',
            display: 'text',
            expose: ['stats'],
            seed: [seed.text('alice', 'cat')],
          }),
          note('rule', 'delete = tombstone · a tombstone keeps its name for ops still on the way'),
          highlight('alice.text@stats'),
          expect('alice.text@stats', { stored: 3, visible: 3 }),
        ),
        step(
          's02',
          'Alice deletes the c, op alice:4. The **tombstone** stays: 3 stored, 2 visible.',
          rga('text').delete('alice', 'alice:1'),
          tomb('alice.text[alice:1]'),
          expect('alice.text', 'at'),
          expect('alice.text@stats', { stored: 3, visible: 2 }),
        ),
        step(
          's03',
          'At the same time Bob inserts h after alice:1. For him the c is alive: chat.',
          rga('text').insertAfter('bob', 'alice:1', 'h'),
          highlight('bob.text[bob:1]'),
          expect('bob.text', 'chat'),
        ),
        step(
          's04',
          'Both broadcast, and the two ops cross.',
          crdt.broadcast('alice', 'text'),
          crdt.broadcast('bob', 'text'),
        ),
        step(
          's05',
          'Bob applies the delete: hat, with one tombstone.',
          apply('alice:4@bob'),
          tomb('bob.text[alice:1]'),
          expect('bob.text', 'hat'),
          expect('bob.text@stats', { stored: 4, visible: 3 }),
        ),
        step(
          's06',
          'Alice applies the insert. The anchor alice:1 is dead but present, so h slots in after it: hat on both.',
          apply('bob:1@alice'),
          highlight('alice.text[bob:1]'),
          same('alice.text', 'bob.text'),
          expect('alice.text', 'hat'),
        ),
        step(
          's07',
          'Alice rewrites the word: she deletes h, a, t and types hey after the last one. Three deletes, three inserts, six ops.',
          clearMarks(),
          rga('text').deleteRange('alice', 'bob:1', 'alice:3'),
          rga('text').type('alice', 'alice:3', 'hey'),
          highlight('alice.text@stats'),
          expect('alice.text', 'hey'),
          expect('alice.text@stats', { stored: 7, visible: 3 }),
        ),
        step(
          's08',
          'She broadcasts; Bob applies all six. Now 7 stored, 3 visible on both: more than half of the text is dead.',
          crdt.broadcast('alice', 'text'),
          applyAll([
            'alice:5@bob',
            'alice:6@bob',
            'alice:7@bob',
            'alice:8@bob',
            'alice:9@bob',
            'alice:10@bob',
          ]),
          same('alice.text', 'bob.text'),
          expect('bob.text', 'hey'),
          expect('bob.text@stats', { stored: 7, visible: 3 }),
        ),
        step(
          's09',
          'Readers never see tombstones, but every copy stores them, ships them and walks past them on every edit. After a week, most of a document can be dead.',
          highlight(['alice.text@stats', 'bob.text@stats'], { tone: 'warn' }),
          callout('bob.text', 'tombstones are not free', { tone: 'warn', sticky: true }),
        ),
        step.long(
          's10',
          'So we want to throw tombstones away. The question is when that is safe: the next scene.',
        ),
      ],
    ),
    scene(
      'safe-to-collect',
      {
        layout: 'triangle',
        actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' }), carol({ icon: 'tablet' })],
      },
      [
        step(
          's01',
          'Three copies of cat. The sidecar now also shows how far each copy has read from each writer: alice 3 so far.',
          crdt.init(['alice', 'bob', 'carol'], 'text', 'rga', {
            wire: 'ops',
            display: 'text',
            expose: ['stats', 'vc'],
            seed: [seed.text('alice', 'cat')],
          }),
          note('rule', 'collect a tombstone only when every copy has seen the delete'),
          highlight(['alice.text@vc', 'bob.text@vc', 'carol.text@vc']),
          expect('alice.text@vc', { alice: 3 }),
        ),
        step(
          's02',
          'Alice deletes the t at the end, op alice:4. She cannot drop the tombstone yet: Bob or Carol may still insert after alice:3.',
          rga('text').delete('alice', 'alice:3'),
          tomb('alice.text[alice:3]'),
          callout('alice.text[alice:3]', 'someone may still point here', { tone: 'warn' }),
          expect('alice.text', 'ca'),
          expect('alice.text@stats', { stored: 3, visible: 2 }),
        ),
        step(
          's03',
          "Carol is offline. Alice broadcasts: Bob applies the delete, and Carol's copy waits at her door.",
          clearMarks(),
          offline('carol'),
          crdt.broadcast('alice', 'text'),
          apply('alice:4@bob'),
          tomb('bob.text[alice:3]'),
          expect('bob.text@vc', { alice: 4 }),
        ),
        step(
          's04',
          'Bob has the tombstone too, but they still cannot drop it. Carol has read alice up to 3, and she could still anchor an op on the t.',
          highlight('carol.text@vc', { tone: 'warn' }),
          callout('carol.text[alice:3]', 'still alive here', { tone: 'warn' }),
          expect('carol.text@vc', { alice: 3 }),
        ),
        step(
          's05',
          'Carol comes online and applies the delete. Now every copy knows the t is dead, and every copy has read alice up to 4.',
          clearMarks(),
          online('carol'),
          apply('alice:4@carol'),
          tomb('carol.text[alice:3]'),
          expect('carol.text@vc', { alice: 4 }),
        ),
        step(
          's06',
          'Alice still needs proof that everyone has seen alice:4. The copies compare how far each has read (simplified): all three tables agree.',
          compare(['alice.text@vc', 'bob.text@vc', 'carol.text@vc'], { expect: 'equal' }),
        ),
        step(
          's07',
          'The tombstone is stable: nothing can still point at it. Alice collects it: 2 stored, 2 visible.',
          clearMarks(),
          crdt.gc('alice', 'text', { upTo: { alice: 4 } }),
          highlight('alice.text@stats'),
          expect('alice.text', 'ca'),
          expect('alice.text@stats', { stored: 2, visible: 2 }),
        ),
        step(
          's08',
          'Bob and Carol collect too. Same text, zero tombstones, on all three.',
          crdt.gc('bob', 'text', { upTo: { alice: 4 } }),
          crdt.gc('carol', 'text', { upTo: { alice: 4 } }),
          allSame('text', ['alice', 'bob', 'carol']),
          expect('bob.text@stats', { stored: 2, visible: 2 }),
          expect('carol.text@stats', { stored: 2, visible: 2 }),
        ),
        step(
          's09',
          'That table of how far each copy has read is a **vector clock**. Unit IV is about it.',
          highlight(['alice.text@vc', 'bob.text@vc', 'carol.text@vc'], { sticky: true }),
        ),
        step.long(
          's10',
          'Few systems prove stability: Yjs and Automerge keep every delete, only smaller (Unit V). Cassandra waits a fixed time, and a node down longer revives rows.',
        ),
      ],
    ),
    scene(
      'collect-too-early',
      { layout: 'pair', actors: [alice({ icon: 'phone' }), bob({ icon: 'laptop' })] },
      [
        step(
          's01',
          'Two copies of cat, synced by state this time (Unit II style). Alice deletes the t, op alice:4: one tombstone.',
          crdt.init(['alice', 'bob'], 'text', 'rga', {
            display: 'text',
            expose: ['stats'],
            seed: [seed.text('alice', 'cat')],
          }),
          note('rule', 'collect a tombstone only when every copy has seen the delete'),
          rga('text').delete('alice', 'alice:3'),
          tomb('alice.text[alice:3]'),
          expect('alice.text', 'ca'),
          expect('alice.text@stats', { stored: 3, visible: 2 }),
        ),
        step(
          's02',
          'Bob is offline and has not seen the delete. Alice is impatient and collects the tombstone without proof (simplified): 2 stored, and no trace of alice:3.',
          offline('bob'),
          crdt.gc('alice', 'text', { unsafe: true }),
          highlight('alice.text@stats'),
          expect('alice.text', 'ca'),
          expect('alice.text@stats', { stored: 2, visible: 2 }),
        ),
        step(
          's03',
          "Bob comes back and they sync their states. Bob's copy still holds the t, alive; Alice's copy has no record of it, dead or alive.",
          online('bob'),
          crdt.sync('alice', 'bob', 'text'),
          expect('alice.text', 'cat'),
          expect('bob.text', 'cat'),
        ),
        step.long(
          's04',
          'Whoops — the t is back on both copies. Merge is a union, Alice had no tombstone to say no, and the delete is lost.',
          cross('alice.text[alice:3]'),
          highlight('bob.text[alice:3]', { tone: 'danger' }),
        ),
        step(
          's05',
          'The fix: never collect without proof that every copy has seen the delete. That is what the last scene did, with the read tables.',
          clearMarks(),
          note('rule', 'collect only with proof: every copy has seen the delete'),
        ),
        step.long(
          's06',
          'This is the Cassandra zombie row: a replica that misses a delete for longer than the grace period revives it on repair. Tombstones are cheap; zombies are not.',
        ),
      ],
    ),
  ],
})
