/**
 * The authoring API of the lesson DSL (docs/animation-dsl.md §8). Pure constructors that return
 * the plain data of `src/lesson/types.ts`; `step()` flattens nested command lists so macros and
 * aliases drop in anywhere a command goes. Every output passes the Zod schema.
 *
 *   import { topic, scene, step, alice, bob, crdt, lww, seed, merge, expect } from '@/lesson/builders'
 */
export { topic, scene, step, flattenCommands, type CommandInput, type SceneOpts } from './structure'
export { alice, bob, carol, dana, server, service, device, board, type ActorOpts } from './actors'
export {
  toValue,
  scalar,
  rec,
  list,
  sset,
  cnt,
  clockOf,
  text,
  table,
  row,
  meter,
  bytes,
  uuid,
  type ValueLike,
  type RecOpts,
  type ListOpts,
  type TextOpts,
  type BytesOpts,
} from './values'
export {
  spawn,
  remove,
  removeBoard,
  layout,
  tick,
  skew,
  offline,
  online,
  status,
  note,
  set,
  patch,
  insert,
  del,
  move,
  sort,
  annotate,
  unannotate,
  view,
  send,
  deliver,
  drop,
  duplicate,
  relay,
  highlight,
  callout,
  conflict,
  compare,
  same,
  check,
  cross,
  clearMarks,
  unmark,
  expect,
  bad,
  good,
  tomb,
  apply,
  merge,
  ref,
  p,
  type NoteOpts,
  type QuietOpts,
  type AnnotateOpts,
  type SendOpts,
  type DeliverOpts,
  type MarkOpts,
} from './commands'
export {
  crdt,
  seed,
  lww,
  lwwMap,
  maxReg,
  mvReg,
  gcounter,
  pncounter,
  opcounter,
  gset,
  twoPSet,
  lwwSet,
  orSet,
  rga,
  vclock,
  lamport,
  hlc,
  doc,
  S,
  DOC_OPS,
  type DocOp,
  type DocPartOps,
  type UpdateOpts,
  type CrdtSendOpts,
  type CrdtBroadcastOpts,
  type CrdtGcOpts,
} from './crdt'
export { syncAll, broadcastState, allSame, applyAll, sendAndDeliver } from './macros'
export { regex, type RegexUntil } from './regex'
